### ISSUE TITLE
New unexpected build failures on 20240603.1.0

### ISSUE THREAD

**Issue by llvm-beanz** [actions/runner-images#10004]
### Description

Our PR builds had been working fine as expected until last night when the runners updated to the 20240603.1.0 image. An impacted PR is here: 

https://github.com/microsoft/DirectXShaderCompiler/pull/6668

Earlier iterations of the PR build successfully, but the builds began failing once the image updated.

See a failing build here:
https://dev.azure.com/DirectXShaderCompiler/public/_build/results?buildId=6383&view=results

And a previously successful one here:
https://dev.azure.com/DirectXShaderCompiler/public/_build/results?buildId=6371&view=results

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: 20240603.1.0
https://dev.azure.com/DirectXShaderCompiler/public/_build/results?buildId=6383&view=results

### Is it regression?

20240514.3.0

### Expected behavior

Our builds should work?
https://dev.azure.com/DirectXShaderCompiler/public/_build/results?buildId=6371&view=results

### Actual behavior

The build fails with errors we don't encounter locally or on older VM images.

### Repro steps

We cannot reproduce outside the VM image.

**Comment by past-due** [comment]
We are also seeing new issues in the `20240603.1.0` Windows Server 2022 image.

Specifically, in our case, a built executable yields an access violation when attempts are made to run it as part of later stages of our build process.

**Comment by Esvandiary** [comment]
We're also seeing issues with `windows-2022` runners starting sometime in the last two days; re-running previously successful jobs consistently result in failures.

In our case, the builds themselves succeed but trying to run any of the resulting executables fails with `Access violation`.

**Comment by ScottTodd** [comment]
We're also seeing similar issues on `windows-2022` with 

* success on old runner version (`20240514.3.0`): https://github.com/iree-org/iree/actions/runs/9401944863/job/25894862559
* failure on new runner version (`20240603.1.0`): https://github.com/iree-org/iree/actions/runs/9404522541/job/25903631922

Errors are all segfaults trying to run executable files.

**Comment by past-due** [comment]
The issue may be due to a combination of the ordering of the PATH environment variable, older versions of vcruntime bundled with Python, and changes in VS 2022 17.10 STL that require the latest vcruntime.

When running the following on `windows-2022:20240603.1.0` I see:
`echo ((Get-Command vcruntime140.dll).Path)` = `C:\hostedtoolcache\windows\Python\3.9.13\x64\vcruntime140.dll`
`echo ((Get-Command vcruntime140.dll).Version)` = `14.29.30139.0`

But the system-installed version (at `C:\Windows\system32\vcruntime140.dll`) is `14.40.33810.00`

As noted in the VS 2022 17.10 STL release notes:
> - Fixed mutex's constructor to be constexpr. https://github.com/microsoft/STL/pull/3824 >   - https://github.com/microsoft/STL/pull/4000 https://github.com/microsoft/STL/pull/4339
>     - Note: Programs that aren't following the documented [restrictions on binary compatibility](https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170) may encounter null dereferences in mutex machinery. You must follow this rule:
>       > When you mix binaries built by different supported versions of the toolset, the Redistributable version must be at least as new as the latest toolset used by any app component.

Reference: https://github.com/microsoft/STL/releases/tag/vs-2022-17.10
Another reference: https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660?sort=active

And, in fact, I can confirm that built executables run correctly on a VM where I've ensured that `vcruntime140.dll` version `14.40.33810.00` is what's loaded.

-----

Possible recommendations for windows images:

- Given https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170, it might make sense to remove any local / applocal copies of the VCruntime files in installed tool paths that end up in the `PATH` environment variable (at least, in the ones that show up before `C:\Windows\system32`). And/or reorder the `PATH` environment variable.

**Comment by firthm01** [comment]
Also seeing segfaults running executables from a windows-latest (20240603.1.0) runner. Was fine on 20240514.3.0.
Private repo so can't share runs, but it looks very similar to the other reports. In our case we're running pluginval.exe against some audio plugins built by the runner. Interestingly not an immediate segfault. Runs through several test phases before failing. 

```
Starting tests in: pluginval / Editor...
D:\a\_temp\7e7e13d1-ac8c-4be7-bda4-e292e2e5bb48.sh: line 3:  1317 Segmentation fault      ./pluginval.exe --strictness-level 10 --verbose --validate "build/plugin/[REDACTED].vst3"
##[error]Process completed with exit code 139.```

**Comment by Esvandiary** [comment]
DLL confusion due to PATH issues makes a lot of sense - I had a build succeed just now simply by changing the workflow to build in Debug rather than Release. The executables would then be looking for `d`-suffixed DLLs in the PATH, which wouldn't conflict.

**Comment by rouault** [comment]
I also see a regression on the GDAL (https://github.com/OSGeo/gdal) CI related to that change, causing crashes during tests execution:

- Last good build: https://github.com/OSGeo/gdal/actions/runs/9392254916/job/25869181603?pr=10145 (Version: 20240514.3.0)
- Failed build: https://github.com/OSGeo/gdal/actions/runs/9404419267/job/25903290692?pr=10149 (Version: 20240603.1.0)

**Comment by mkruskal-google** [comment]
We hit this too and traced it back to mutex usage.  This looks like https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660#T-N10668856, which suggests an older incompatible version of msvcp140.dll is being used in this image.

**Comment by bduffany** [comment]
20240603.1.0 broke us too; it looks like a similar mysterious executable error as other folks are mentioning:

* Failing: https://github.com/buildbuddy-io/buildbuddy/actions/runs/9406760840/job/25910946394
* Good: https://github.com/buildbuddy-io/buildbuddy/actions/runs/9402894773/job/25898065564

**Comment by rouault** [comment]
> * Given https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170, it might make sense to remove any local / applocal copies of the VCruntime files in installed tool paths that end up in the `PATH` environment variable (at least, in the ones that show up before `C:\Windows\system32`). And/or reorder the `PATH` environment variable.

I've attempted that in https://github.com/rouault/gdal/actions/runs/9407632196/job/25913839874, copying c:\Windows\system32\vcruntime140.dll in a specific directory and putting it in front of the path, but it appears that the version of c:\Windows\system32\ is only 14.32.31326 , and not >= 14.40.33810.00. I would argue that the runner-image should be fixed to have a recent enough vcruntime140.dll in front of the PATH.

A workaround I found when reading https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660#T-N10668856 is that you can define "/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR" when building your software to revert to a std::mutex constructor compatible of older vcruntimes : https://github.com/rouault/gdal/commit/c4ab31f0eb1c196dff2d561292a29d8840223790 . My builds work fine with that workaround.

**Comment by ScottTodd** [comment]
Can we expect a rollback or some other fix to the runner images, or will affected projects need to use one of the listed workarounds? Is there a way to use older/stable runner images instead of this new version?

**Comment by randombit** [comment]
Seeing this also

Runner image 20240514.3.0 works fine

https://github.com/randombit/botan/actions/runs/9408188903/job/25918967600

Runner image 20240603.1.0, built binaries fail with error code 3221225477

https://github.com/randombit/botan/actions/runs/9408188903/job/25918967856

Same code in this case; one (working) is the PR the second (failing) is the merge of that PR into master.

**Comment by YOU54F** [comment]
Getting similar errors today with the new images, simply executing curl to download a binary. affecting windows-2019 and windows-2022 images. ( I was using windows-latest, but tried windows-2019, same result)

```
🔵  Downloading ffi v0.4.24 for pact_ffi-windows-x86_64.dll.gz
Error: Process completed with exit code 43.
```

Here is a re-run of job today, using a newer runner, that passed yesterday.

🟢 `20240514.3.0` - https://github.com/YOU54F/pact-js-core/actions/runs/9392917514/job/25868610705#step:1:9
🔴 `20240603.1.0` - https://github.com/YOU54F/pact-js-core/actions/runs/9392917514/job/25920895001#step:1:9

**Comment by ijunaidm** [comment]
@llvm-beanz - Kindly re-run the pipeline now. And also if you face same error again, please share the yaml script/snippet for Building task from the pipeline.

**Comment by kubo990** [comment]
I also see failed pipelines in new build [20240603.1.0]. Errors in solution restore task:
`C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(154,5): 
error NETSDK1145: The Apphost pack is not installed and NuGet package restore is not supported. 
Upgrade Visual Studio, remove global.json if it specifies a certain SDK version, and uninstall the newer SDK. 
For more options visit   https://aka.ms/targeting-apphost-pack-missing  Pack Type:Apphost, Pack directory: 
C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x86, targetframework: net7.0, Pack PackageId: 
Microsoft.NETCore.App.Host.win-x86, Pack Package Version: 7.0.19 [D:\***.vcxproj]
`
Is it related to some issues on host machine or some changes should be done on our end? Projects use .NET 7, but host machine seems uses .NET SDK 8.

**Comment by kishorekumar-anchala** [comment]
> I also see failed pipelines in new build [20240603.1.0]. Errors in solution restore task: `C:\Program Files\dotnet\sdk\8.0.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(154,5): error NETSDK1145: The Apphost pack is not installed and NuGet package restore is not supported. Upgrade Visual Studio, remove global.json if it specifies a certain SDK version, and uninstall the newer SDK. For more options visit https://aka.ms/targeting-apphost-pack-missing Pack Type:Apphost, Pack directory: C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Host.win-x86, targetframework: net7.0, Pack PackageId: Microsoft.NETCore.App.Host.win-x86, Pack Package Version: 7.0.19 [D:\***.vcxproj] ` Is it related to some issues on host machine or some changes should be done on our end? Projects use .NET 7, but host machine seems uses .NET SDK 8.

@kubo990 ,  It would be helpful if you share the vsbuild stage yaml script . also confirm in which SDK your application developed.

**Comment by Arech** [comment]
This has broken all Windows-based Azure pipelines in our Company and everyone is halted. I wonder how much would it cost for us...

**Comment by henryruhs** [comment]
I think `windows-next` would be a good idea in the future... Just roll it back guys!

**Comment by kubo990** [comment]
> @kubo990 , It would be helpful if you share the vsbuild stage yaml script . also confirm in which SDK your application developed.

@kishorekumar-anchala Application targets .NET 7 SDK. Workaround was adding UseDotNet task with specifing/installing sdk 7.0, however I don't think that it should be needed, according to doc, SDK 7.0 should be still installed on windows-2022 agent.

```
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 7.x'
  inputs:
    version: 7.x
```

there are no special commands in yaml pipeline. it fails on nuget restore task. 
```
name: $(Build.BuildId)

pool:
  vmImage: 'windows-2022'

trigger:
  - 'develop'

pr:
  - 'develop'

 
steps:
***(some powershell not related tasks)
    
- task: NuGetCommand@2
  displayName: 'Restore NuGet Packages'
  inputs:
    restoreSolution: 'SolutionName.sln'

*** build tasks
```
`

**Comment by saran-t** [comment]
There's a copy of `vcruntime140.dll` version 14.40.33810 in `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\14.40.33807\x64\Microsoft.VC143.CRT`.

Adding this to `GITHUB_PATH` doesn't seem to help in my case, my tests are still failing with `unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.`, but perhaps this might be useful to someone else.

**Comment by jviotti** [comment]
Is there a workaround other than doing debug builds? This is heavily impacting pipelines of many of our projects and we definitely need Windows doing builds and packages on CI

**Comment by mwestphal** [comment]
Also affected over at https://github.com/f3d-app/f3d/

**Comment by saran-t** [comment]
OK, copying all DLLs from `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\14.40.33807\x64\Microsoft.VC143.CRT` to the same directory as the test binaries fixed the issue for me.

I added the following stage between building and testing, `bin\Release` is where all the test binaries live.

```Copy-Item (Join-Path `
    ((Get-ChildItem -Directory `
        -Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Redist\MSVC\14.*" |
      Sort -Descending | Select-Object -First 1).FullName
    ) 'x64\Microsoft.VC143.CRT\*.dll') "bin\Release"```

**Comment by dneto0** [comment]
Aside from needing to fix the image, I guess this also means there should be a smoke test for any new image roll out.

**Comment by dneto0** [comment]
> @llvm-beanz - Kindly re-run the pipeline now. And also if you face same error again, please share the yaml script/snippet for Building task from the pipeline.

I was the original reporter to @llvm-beanz 

A colleague ran a similar pipeline starting about 20 minutes ago, for https://github.com/microsoft/DirectXShaderCompiler/pull/6679 
The Azure pipepline for a VS2022 release build is: https://github.com/microsoft/DirectXShaderCompiler/pull/6679/checks?check_run_id=25949596545 
It failed after 6 minutes, with raw log https://dev.azure.com/DirectXShaderCompiler/5060fecd-942c-4880-bb20-b8b29e0cbfe1/_apis/build/builds/6389/logs/50 

I believe  Azure pipeline is defined in https://github.com/microsoft/DirectXShaderCompiler/blob/main/azure-pipelines.yml

**Comment by dneto0** [comment]
Looks like it affects another project.

This PR: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/pull/2598 
This job: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/actions/runs/9419555155/job/25949562007?pr=2598 
This workflow: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/7d6d66975ff394a18e60db2e83aa872b65180248/.github/workflows/check-in-tree-build.yml#L110 

It's doing a release build with VS2022, and the symptom is:
```
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(254,5): error MSB8066: Custom build for 'D:\a\SPIRV-LLVM-Translator\SPIRV-LLVM-Translator\build\CMakeFiles\8bc6b7dc048b6551197d3c360a7ac54d\ARMTargetParserDef.inc.rule;D:\a\SPIRV-LLVM-Translator\SPIRV-LLVM-Translator\build\CMakeFiles\edf72b9a29a2179a19058e3c565d1071\ARMTargetParserTableGen.rule;D:\a\SPIRV-LLVM-Translator\SPIRV-LLVM-Translator\llvm-project\llvm\include\llvm\TargetParser\CMakeLists.txt' exited with code -1073741819. [D:\a\SPIRV-LLVM-Translator\SPIRV-LLVM-Translator\build\include\llvm\TargetParser\ARMTargetParserTableGen.vcxproj]
```
Basically, `error MSB8066: Custom build  ... exited with code -1073741819. `  I've seen that exit code across many affected jobs.

**Comment by guusw** [comment]
Same things, had to update our LLVM toolchain to 17.0+ because of updated SDK headers, now every application built with that toolchain fails to run with a segfault:
https://github.com/fragcolor-xyz/shards/actions/runs/9416413387/job/25940571766

I downloaded the built binary and ran the application on my owned system and it ran without problems.

Seems indeed like a runtime dll issue.

**Comment by mmomtchev** [comment]
I was able to run it in with MSVC ASAN enabled: https://github.com/mmomtchev/magickwand.js/actions/runs/9422296093/job/25958255145

The faulty DLL is `C:\Windows\SYSTEM32\MSVCP140.dll`

I don't have the problem with debug builds.

**Comment by sudara** [comment]
I'm seeing this issue across many repositories. Can confirm that passing this to cmake is a functioning workaround: `-DCMAKE_CXX_FLAGS=" /D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR"`

**Comment by bdashore3** [comment]
I've had this issue as well. If rolling back is an option, here's how I did it:

Install the last version of VS build tools 17.9 with this block in your YAML:

```yml
- name: Install VS2022 BuildTools 17.9.7
  run: choco install -y visualstudio2022buildtools --version=117.9.7.0 --params "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --installChannelUri https://aka.ms/vs/17/release/180911598_-255012421/channel"
  if: runner.os == 'Windows'
```

The `--installChannelUri` param is used due to this issue: https://github.com/jberezanski/ChocolateyPackages/issues/100

When building, activate the VS dev shell in the same run step (I'm not sure how to persist the dev shell activation across run steps. Copying the PATH didn't seem to help)

```yaml
# --- Spawn the VS shell
if ($IsWindows) {
  Import-Module 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll'
  Enter-VsDevShell -VsInstallPath 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools' -DevCmdArguments '-arch=x64 -host_arch=x64'

  # Used for python building
  $env:DISTUTILS_USE_SDK=1
}
```

A full example is located on my [ExllamaV2 fork](https://github.com/bdashore3/exllamav2/blob/master/.github/workflows/build-wheels-release.yml#L122) which had problems building on VS build tools v17.10.

**Comment by MarkCallow** [comment]
Our builds are affected too with many in-flight PR's stalled. In our case the exceptions are all 0xC0000005 which occurs when there is a problem loading a dependent DLL which chimes with the DLL version issues described earlier.

Needs an urgent fix. Please scrap this update, roll back to 20240514.3.0 wait until you have a proper fix before updating again.

**Comment by odygrd** [comment]
Also having the same issue 

adding this line fixed it for my project 

target_compile_definitions(${target_name} _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR)

https://github.com/odygrd/quill/commit/9cd69094c513e536b5ad1e7a0fbc92174a1a9cf7

**Comment by llvm-beanz** [comment]
@ijunaidm, the traffic on this issue suggests this is a widespread problem. Can you please roll back the image to the older version while you sort this out so that further disruption can be avoided?

Faulty CI for an extended period of time results in huge and expensive productivity disruptions.

**Comment by llvm-beanz** [comment]
@ashtom we’re two days into a significant outage caused by an image update to the GitHub Actions and Azure Pipelines Windows Images.

**Comment by Sedeniono** [comment]
Well, I also ran into the mutex problem with release builds. From a crash dump of my executable I can clearly see that it is using the VS 17.10 STL headers (`_MSVC_STL_UPDATE==202402`) and that `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` is not defined. As a result, the [`constexpr` constructor of `std::mutex`](https://github.com/microsoft/STL/blob/d6efe9416e4ad7d6e245ae9e96023d413794d1eb/stl/inc/mutex#L40) is called, which initializes `_Mtx_storage._Critical_section` with zeros. The non-constexpr constructor would call `_Mtx_init_in_situ()` which is [not just zero-initializing things](https://github.com/microsoft/STL/blob/d6efe9416e4ad7d6e245ae9e96023d413794d1eb/stl/src/mutex.cpp#L41). The gotcha: When e.g. `std::mutex::lock()` is called, the code lives in the msvcp140.dll. In the crash dump I can clearly see that it is using `"C:\Windows\System32\msvcp140.dll"` which is at version `14.32.313260.0`. This corresponds to the STL shipped with VS 17.2. And that dll basically assumes that the mutex internals are "properly" initialized with `_Mtx_init_in_situ()`. But they aren't.

As mentioned @past-due [here](https://github.com/actions/runner-images/issues/10004#issuecomment-2153091255), VS 17.10 STL breaks the ABI compatiblity (specifically in https://github.com/microsoft/STL/pull/4339).

**Comment by MarkCallow** [comment]
GitHub staff, please conduct a post-mortem into how this breakage happened and take steps, e.g. improved testing, to ensure such breakages do not happen again.

**Comment by mmomtchev** [comment]
> GitHub staff, please conduct a post-mortem into how this breakage happened and take steps, e.g. improved testing, to ensure such breakages do not happen again.

Although I agree that the Github team should probably compile some non-trivial software with their runner images before deploying, the underlying issue is the Microsoft one. DLLs are versioned so that this does not happen. This can happen to your users too - if they don't have the correct DLL, they will have a crash.

This means that the only to ensure that those binaries work is to include this runtime in the package. I might as well link it statically in this case, why I use a shared library at all. Microsoft, what have you done.

**Comment by lelegard** [comment]
+1 as many, previously reported as #10020, before I was redirected to this one.

The justifications from Microsoft about the proposed workaround are really pathetic. They created a huge mess on the build + test + deployment and when many users complain about a crash, they close it as "by design". By design !!! And they propose no reliable way to always select the "right" VC redistributable so that it works.

Sorry about that, GitHub team, it is probably not your fault. But all users need a reliable CI pipeline for C++ applications to build and test. And, as of today, it is simply broken. Fully broken.

I am not the only one to ask for this here: Please revert to the previous runner image until you find a way to build a reliable runner image for C++ applications with the new versions.

**Comment by lelegard** [comment]
@Sedeniono 
> Can't the Windows runner simply also have the latest redistributable installed? That should fix the issue.

I thought it would, but it seems more complicated than that. 

In the workflow, before building the C++ app, I search the "VC redistributable package" which comes with the VS I use for the build and installed it before building. So the scenario of the workflow is 

1. Locate `MSBuild.exe` and `vc_redist.x64.exe` from the current VS install. In that case, they are both found under `C:\Program Files\Microsoft Visual Studio\2022\Community`
2. Install `vc_redist.x64.exe`
3. Build the C++ application using `MSBuild.exe`
4. Run the application => still fails the same way

See a demonstrator here: https://github.com/lelegard/gh-runner-lock-2

So, the problem is worse than that. Even if you install the same VC runtime as used for the compilation, it does not work either.

**Comment by lelegard** [comment]
Currently, inside a GH runner, the list of `Path` elements with MSVC DLL's and their version information is:

~~~
C:\Program Files\PowerShell\7
    C:\Program Files\PowerShell\7\vcruntime140_cor3.dll => 14.38.33130.0
C:\Program Files\MongoDB\Server\5.0\bin
C:\aliyun-cli
C:\vcpkg
C:\Program Files (x86)\NSIS\
C:\tools\zstd
C:\Program Files\Mercurial\
    C:\Program Files\Mercurial\msvcm90.dll => 9.00.30729.9518
    C:\Program Files\Mercurial\msvcp90.dll => 9.00.30729.9518
    C:\Program Files\Mercurial\msvcr90.dll => 9.00.30729.9518
C:\hostedtoolcache\windows\stack\2.15.7\x64
C:\cabal\bin
    ==> non existent
C:\\ghcup\bin
C:\mingw64\bin
C:\Program Files\dotnet
C:\Program Files\MySQL\MySQL Server 8.0\bin
C:\Program Files\R\R-4.4.0\bin\x64
C:\SeleniumWebDrivers\GeckoDriver
C:\SeleniumWebDrivers\EdgeDriver\
C:\SeleniumWebDrivers\ChromeDriver
C:\Program Files (x86)\sbt\bin
C:\Program Files (x86)\GitHub CLI
    ==> non existent
C:\Program Files\Git\bin
C:\Program Files (x86)\pipx_bin
C:\npm\prefix
C:\hostedtoolcache\windows\go\1.21.10\x64\bin
C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts
C:\hostedtoolcache\windows\Python\3.9.13\x64
    C:\hostedtoolcache\windows\Python\3.9.13\x64\vcruntime140_1.dll => 14.29.30139.0 built by: vcwrkspc
    C:\hostedtoolcache\windows\Python\3.9.13\x64\vcruntime140.dll => 14.29.30139.0 built by: vcwrkspc
C:\hostedtoolcache\windows\Ruby\3.0.7\x64\bin
C:\Program Files\OpenSSL\bin
C:\tools\kotlinc\bin
C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.412-8\x64\bin
    C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.412-8\x64\bin\msvcp140.dll => 14.16.27033.0 built by: vcwrkspc
    C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.412-8\x64\bin\vcruntime140.dll => 14.16.27033.0 built by: vcwrkspc
C:\Program Files\ImageMagick-7.1.1-Q16-HDRI
    C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\msvcp140_1.dll => 14.38.33135.0
    C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\msvcp140_2.dll => 14.38.33135.0
    C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\msvcp140_atomic_wait.dll => 14.38.33135.0
    C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\msvcp140_codecvt_ids.dll => 14.38.33135.0
    C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\msvcp140.dll => 14.38.33135.0
    C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\vcruntime140_1.dll => 14.38.33135.0
    C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\vcruntime140_threads.dll => 14.38.33135.0
    C:\Program Files\ImageMagick-7.1.1-Q16-HDRI\vcruntime140.dll => 14.38.33135.0
C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin
C:\ProgramData\kind
C:\ProgramData\docker-compose
C:\ProgramData\Chocolatey\bin
C:\Windows\system32
    C:\Windows\system32\msvcirt.dll => 7.0.20348.1 (WinBuild.160101.0800)
    C:\Windows\system32\msvcp_win.dll => 10.0.20348.1 (WinBuild.160101.0800)
    C:\Windows\system32\msvcp110_win.dll => 10.0.20348.1 (WinBuild.160101.0800)
    C:\Windows\system32\msvcp120_clr0400.dll => 12.00.52519.0 built by: VSWINSERVICING
    C:\Windows\system32\msvcp120.dll => 12.00.40660.0 built by: VSULDR
    C:\Windows\system32\msvcp140_1.dll => 14.32.31326.0
    C:\Windows\system32\msvcp140_1d.dll => 14.40.33810.0
    C:\Windows\system32\msvcp140_2.dll => 14.32.31326.0
    C:\Windows\system32\msvcp140_2d.dll => 14.40.33810.0
    C:\Windows\system32\msvcp140_atomic_wait.dll => 14.32.31326.0
    C:\Windows\system32\msvcp140_clr0400.dll => 14.32.31326.0
    C:\Windows\system32\msvcp140_codecvt_ids.dll => 14.32.31326.0
    C:\Windows\system32\msvcp140.dll => 14.32.31326.0
    C:\Windows\system32\msvcp140d_atomic_wait.dll => 14.40.33810.0
    C:\Windows\system32\msvcp140d_codecvt_ids.dll => 14.40.33810.0
    C:\Windows\system32\msvcp140d.dll => 14.40.33810.0
    C:\Windows\system32\msvcp60.dll => 7.0.20348.1 (WinBuild.160101.0800)
    C:\Windows\system32\msvcr100_clr0400.dll => 14.8.9037.0 built by: NET481REL1
    C:\Windows\system32\msvcr120_clr0400.dll => 12.00.52519.0 built by: VSWINSERVICING
    C:\Windows\system32\msvcr120.dll => 12.00.40660.0 built by: VSULDR
    C:\Windows\system32\msvcrt.dll => 7.0.20348.1 (WinBuild.160101.0800)
    C:\Windows\system32\vcruntime140_1_clr0400.dll => 14.32.31326.0
    C:\Windows\system32\vcruntime140_1.dll => 14.32.31326.0
    C:\Windows\system32\vcruntime140_1d.dll => 14.40.33810.0
    C:\Windows\system32\vcruntime140_clr0400.dll => 14.32.31326.0
    C:\Windows\system32\vcruntime140_threads.dll => 14.40.33810.0
    C:\Windows\system32\vcruntime140_threadsd.dll => 14.40.33810.0
    C:\Windows\system32\vcruntime140.dll => 14.32.31326.0
    C:\Windows\system32\vcruntime140d.dll => 14.40.33810.0
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files\dotnet\
C:\Program Files\PowerShell\7\
    C:\Program Files\PowerShell\7\vcruntime140_cor3.dll => 14.38.33130.0
C:\Program Files\Microsoft\Web Platform Installer\
C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
C:\Program Files\Microsoft SQL Server\150\Tools\Binn\
C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\
    C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\vcruntime140_cor3.dll => 14.29.30139.0 built by: vcwrkspc
C:\Program Files (x86)\WiX Toolset v3.14\bin
C:\Program Files\Microsoft SQL Server\130\DTS\Binn\
C:\Program Files\Microsoft SQL Server\140\DTS\Binn\
    ==> non existent
C:\Program Files\Microsoft SQL Server\150\DTS\Binn\
    ==> non existent
C:\Program Files\Microsoft SQL Server\160\DTS\Binn\
    ==> non existent
C:\Strawberry\c\bin
C:\Strawberry\perl\site\bin
C:\Strawberry\perl\bin
C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin
C:\Program Files\TortoiseSVN\bin
C:\Program Files\CMake\bin
C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.7\bin
C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code
    C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\msvcp110.dll => 11.00.65501.17010 built by: WINCCOMP(CGTBUILD13-VCWRKSPC)
    C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\msvcp140_1.dll => 14.25.28508.3 built by: vcwrkspc
    C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\msvcp140_2.dll => 14.25.28508.3 built by: vcwrkspc
    C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\msvcp140.dll => 14.00.23026.0 built by: WCSETUP
    C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\msvcr110.dll => 11.00.65501.17010 built by: WINCCOMP(CGTBUILD13-VCWRKSPC)
    C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\vcruntime140_1.dll => 14.25.28508.3 built by: vcwrkspc
    C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code\vcruntime140.dll => 14.00.23026.0 built by: WCSETUP
C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager
C:\Program Files\nodejs\
C:\Program Files\Git\cmd
C:\Program Files\Git\mingw64\bin
C:\Program Files\Git\usr\bin
C:\Program Files\GitHub CLI\
c:\tools\php
C:\Program Files (x86)\sbt\bin
C:\Program Files\Amazon\AWSCLIV2\
    C:\Program Files\Amazon\AWSCLIV2\VCRUNTIME140.dll => 14.38.33126.1
C:\Program Files\Amazon\SessionManagerPlugin\bin\
C:\Program Files\Amazon\AWSSAMCLI\bin\
C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
C:\Program Files\LLVM\bin
    C:\Program Files\LLVM\bin\msvcp140_1.dll => 14.29.30139.0 built by: vcwrkspc
    C:\Program Files\LLVM\bin\msvcp140_2.dll => 14.29.30139.0 built by: vcwrkspc
    C:\Program Files\LLVM\bin\msvcp140_atomic_wait.dll => 14.29.30139.0 built by: vcwrkspc
    C:\Program Files\LLVM\bin\msvcp140_codecvt_ids.dll => 14.29.30139.0 built by: vcwrkspc
    C:\Program Files\LLVM\bin\msvcp140.dll => 14.29.30139.0 built by: vcwrkspc
    C:\Program Files\LLVM\bin\vcruntime140_1.dll => 14.29.30139.0 built by: vcwrkspc
    C:\Program Files\LLVM\bin\vcruntime140.dll => 14.29.30139.0 built by: vcwrkspc
C:\Users\runneradmin\.dotnet\tools
C:\Users\runneradmin\.cargo\bin
C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps
~~~

This is a bit of a mess. There is no real confidence in which MSVC runtime will be used.

The result was obtained in a workflow with this command:
~~~
foreach ($d in ($env:Path -split ';')) {
    Write-Output "$d"
    if (-not -not $d) {
        if (Test-Path -PathType Container $d) {
            Get-ChildItem "$d\*" -Include @("vcruntime*.dll", "msvc*.dll") |
                ForEach-Object { (Get-Command $_).FileVersionInfo } |
                ForEach-Object { Write-Output "    $($_.FileName) => $($_.FileVersion)" }
        }
        else {
            Write-Output "    ==> non existent"
        }
    }
}
~~~

**Comment by MarkCallow** [comment]
> Although I agree that the Github team should probably compile some non-trivial software with their runner images before deploying,

Compilation isn't the issue here. Running the compiled software is. They need to build _and run_ some non-trivial software. (In my case the crashes happen whenever the applications that are being tested use std:mutex. If the test takes the app through a path that does not use std::mutex then it runs fine.)

**Comment by a-zakir** [comment]
Github what have you done!?
We’re facing ugly seg faults 
https://github.com/AntaresSimulatorTeam/Antares_Simulator/actions/runs/9414209107/job/25932593109

**Comment by a-zakir** [comment]
> > Although I agree that the Github team should probably compile some non-trivial software with their runner images before deploying,
> 
> Compilation isn't the issue here. Running the compiled software is. They need to build _and run_ some non-trivial software. (In my case the crashes happen whenever the applications that are being tested use std:mutex. If the test takes the app through a path that does not use std::mutex then it runs fine.)

This is a weak assumption, what’s make you think that « they »are not Sufficiently test mutex ?

**Comment by FangCunWuChang** [comment]
I hit this too, then protoc returned 0xc0000142

**Comment by agarny** [comment]
Also affected by this issue and, like some others here, the `/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` workaround solved it for me. What a waste of time though! :exploding_head:

**Comment by MarkCallow** [comment]
> > Compilation isn't the issue here. Running the compiled software is. They need to build _and run_ some non-trivial software. (In my case the crashes happen whenever the applications that are being tested use std:mutex. If the test takes the app through a path that does not use std::mutex then it runs fine.)
> 
> This is a weak assumption, what make you think that « they »are not Sufficiently test mutex ?

I didn't claim they are insufficiently testing mutex. I simply said that in my case that is where the crash is happening. I do claim that they are insufficiently testing running software built with and running in the new runner environment.

Whatever the cause, the point is that a major breakage made it through their test and release system all the way to the production runner image without being detected. This is why I am requesting they conduct a post-mortem so they can figure out why and put in place steps to prevent it happening again.

**Comment by shamil-mubarakshin** [comment]
Hello, we have identified a possible cause of DLL's version mismatch. `TortoiseSVN` tool when installed after `VStudio` overwrites files such as `vcruntime140.dll` and `MSVCP140.dll` under `c:\Windows\system32`. With [PR](https://github.com/actions/runner-images/pull/10010) DLLs are of the latest version which I have tested on two projects:
1. It fixes @ScottTodd 's segfaults when run from https://github.com/iree-org/iree/commit/29472a1637146514c2781c3befca34939c6e7480
2. Partially fixes @llvm-beanz's build issues https://github.com/microsoft/DirectXShaderCompiler. `Release` stage completes, `Debug` stage ends in `warning C4201: nonstandard extension used: nameless struct/union` treated as an error

We will start deployment with mentioned fix this week

**Comment by lelegard** [comment]
@agarny 
> Also affected by this issue and, like some others here, the /D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR workaround solved it for me. What a waste of time though! 🤯

It's more than a waste of time in the past few days (2 full days for me, multiplied by a few hundredths people in the same situation, meaning a loss of a couple man.years overall), it is also a waste of future time, because this "workaround" increases the technical debt. It forces an old behaviour in software, that will fall into oblivion, until it breaks in some future release, when the forced legacy behaviour becomes obsolete. And developers will spend hours tracking the issue, until they discover the old workaround and disable it, finally.

Really, thank you MS and GH for the situation...

**Comment by MarkCallow** [comment]
I added the following to my CI run to check vcruntime140 versions:

```
((Get-Command vcruntime140.dll).Path)
C:\hostedtoolcache\windows\Python\3.9.13\x64\vcruntime140.dll
((Get-Command vcruntime140.dll).Version)

Major  Minor  Build  Revision
-----  -----  -----  --------
14     29     30139  0

((Get-Command C:/Windows/system32/vcruntime140.dll).Version)
14     32     31326  0
```

From this we see that (a) the runtime found on $env.PATH is an old one from the Python installation and (b) that the runtime installed in system32 is also old. 14.40.33810 is apparently needed for constexpr mutexes.

On my local Windows, which has VS Community, 14.40.33810 is installed in `C:/Windows/system32`.

It looks like `C:/Windows/system32` has not been updated to the latest. Even if it was, builds will likely fail due to the old version included with Python.

**Comment by MarkCallow** [comment]
> Hello, we have identified a possible cause of DLL's version mismatch. `TortoiseSVN` tool when installed after `VStudio` overwrites files such as `vcruntime140.dll` and `MSVCP140.dll` under `c:\Windows\system32`. With [PR](https://github.com/actions/runner-images/pull/10010) DLLs are of the latest version which I have tested on two projects:

What about the older version from Python that appears earlier in `$env.PATH`?

**Comment by lelegard** [comment]
> > Hello, we have identified a possible cause of DLL's version mismatch. `TortoiseSVN` tool when installed after `VStudio` overwrites files such as `vcruntime140.dll` and `MSVCP140.dll` under `c:\Windows\system32`. With [PR](https://github.com/actions/runner-images/pull/10010) DLLs are of the latest version which I have tested on two projects:
> 
> What about the older version from Python that appears earlier in `$env.PATH`?

+1, yes please, after all installations in the image, make sure that C:\Windows\System32 always comes first in `Path`.

**Comment by agarny** [comment]
> @agarny
> 
> > Also affected by this issue and, like some others here, the /D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR workaround solved it for me. What a waste of time though! 🤯
> 
> It's more than a waste of time in the past few days (2 full days for me, multiplied by a few hundredths people in the same situation, meaning a loss of a couple man.years overall), it is also a waste of future time, because this "workaround" increases the technical debt. It forces an old behaviour in software, that will fall into oblivion, until it breaks in some future release, when the forced legacy behaviour becomes obsolete. And developers will spend hours tracking the issue, until they discover the old workaround and disable it, finally.
> 
> Really, thank you MS and GH for the situation...

Yes, I implemented the two workarounds mentioned [here](https://github.com/actions/runner-images/issues/10004#issuecomment-2153445161) and [here](https://github.com/actions/runner-images/issues/10004#issuecomment-2155695838), and it worked fine for most of my tests, except for one where I need to build some Python bindings using `pip install .`. So, in the end, I decided to disable all of my Windows-related builds/tests. 🙄

I think that, overall, I lost the equivalent of nearly 3 working days (incl. a few hours here and there during my weekend!). I first experienced the issue after I upgraded a third-party library, so this is where I focussed my efforts, not thinking for a second that it could have been a GitHub-hosted Windows runner issue. Lesson learned!

**Comment by raimund-schluessler** [comment]
> We will start deployment with mentioned fix this week

Given the high volume of traffic in this issue, the consequences it entails (completely unusable workflows) and the impractical "workarounds", I would say this doesn't need a scheduled fix somewhen, but an urgent hotfix or rollback now.

**Comment by nibanks** [comment]
This is also breaking most all of our GoogleTest runs in [microsoft/msquic](https://github.com/microsoft/msquic/actions/runs/9411495633/job/25925006514#step:9:52). I agree with the comments above that this must be addressed ASAP.

**Comment by mprather** [comment]
We are running into null exception errors when trying to run some command-line tools that we build. Error reported:

```
Cmd.exe exited with code '-1073741819'.
```

We've checked all code paths since May 26, which is the date of the last successful windows build. We've gone through the painstaking process of running each commit since to see if we can isolate the fix. Nothing works. Finally, I decided to run the May 26 build and it now fails as well. It's not our code. It's the environment.  This is a blocking issue as there are no workarounds available as we can't even get our tools to run (other than just not run any pipelines).

**Comment by lelegard** [comment]
@mprather, welcome to the club 😟

If your applications are written in C++ and use mutexes, you may try to compile with the symbol which disables the constexpr constructor (see details in previous posts).

**Comment by anton-danielsson** [comment]
We are also in the club.
Two workarounds: 

- Setting `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`, or
- linking statically to the vc runtime.

But even better if the runner image is fixed.

**Comment by mprather** [comment]
> If your applications are written in C++ and use mutexes, you may try to compile with the symbol which disables the constexpr constructor (see details in previous posts).

Thanks for the heads up. None of our code explicitly calls std::mutex but the libraries we depend on most likely do. I will have to scan our cached list of vcpkg binaries and determine the next course of action. Nice week and half of debugging pipeline failures, first gcc-13 was pulled, then clang on ubuntu fails, and now windows. All failures because the underlying images have been altered significantly.

**Comment by Vertexwahn** [comment]
Same problems here: https://github.com/Vertexwahn/FlatlandRT/runs/25907600653
For debug builds the problem does not happen. VS 2019 is not affected.

**Comment by N-Dekker** [comment]
When an executable is built with VS 2022 17.10 (Release, x64) + `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`, and linking _dynamically_ to the vc runtime, is it then compatible with the latest Visual C++ Redistributable Version (14.40.33810.0)?

**Comment by llvm-beanz** [comment]
Issues #10019 and #10020, are the same root problem here. Is there any update on a resolution to fix these images?

**Comment by agarny** [comment]
It looks like things are back to normal...?

**Comment by agarny** [comment]
> It looks like things are back to normal...?

Well, not quite. [Two of my Windows tests now work again but another still fails.](https://github.com/opencor/libopencor/actions/runs/9455856328)

**Comment by raimund-schluessler** [comment]
We got runner image `20240610.1.0` this morning:
![grafik](https://github.com/actions/runner-images/assets/2496460/804d8f7b-36bc-45e0-995e-dd84680d8418)

and the error `error: SEH exception with code 0xc0000005 thrown in the test body.` does not occur anymore.

**Comment by agarny** [comment]
> We got runner image `20240610.1.0` this morning:

That's indeed the runner image used by two of my tests (after I rerun them), but my other test still uses the faulty runner image for some reasons (!?). Well, better push another commit...

**Comment by MarkCallow** [comment]
@agarny did you succeed. I just pushed a commit to one of my branches/PRs and it still used the bad 20240603.1.0 image. How to you make it use the new image?

**Comment by rouault** [comment]
> I just pushed a commit to one of my branches/PRs and it still used the bad 20240603.1.0 image. How to you make it use the new image?

You probably just need patience. https://github.com/actions/runner-images/ shows ![image](https://github.com/actions/runner-images/assets/1192433/598e5535-d009-4da5-9392-067a5ce8f99c) . I suspect that it gets deployed on VMs by chunks and in the transition you randomly get either 20240603 or 20240610

**Comment by agarny** [comment]
> @agarny did you succeed. I just pushed a commit to one of my branches/PRs and it still used the bad 20240603.1.0 image. How to you make it use the new image?

I didn't. It also used the 20240603.1.0 runner image even though it used the 20240610.1.0 runner image earlier *when* re-running previously failing tests. So, yeah, I gave up on trying to understand what happened. Best to wait for an official announcement.

**Comment by pthom** [comment]
For information, I just closed a related issue because it was fixed in the previous minutes. See https://github.com/actions/runner/issues/3331

The fix I mention is relative to this:
> A workaround I found when reading https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660#T-N10668856 is that you can define "/D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR" when building your software to revert to a std::mutex constructor compatible of older vcruntimes : https://github.com/rouault/gdal/commit/c4ab31f0eb1c196dff2d561292a29d8840223790 . My builds work fine with that workaround.

`DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` seems to not be needed anymore.

**Comment by MarkCallow** [comment]
Tests of my project's Java binding still fail in 2024.06.10.1.0 as reported by @rouault in #10055. Personally I wouldn't have opened a new bug as to me it is part of the breakage introduced by 2024.06.03.1.0 so covered here. Surprisingly the test of my project's Python binding now works. Surprising because the first `vcruntime140.dll` in `$env:PATH` is still the old one in `C:\hostedtoolcache\windows\Python\3.9.13\x64\vcruntime140.dll`. I will have to check if my Python binding test is exercising any of the multithreaded code in the underlying library.

**Comment by agarny** [comment]
> Tests of my project's Java binding still fail in 2024.06.10.1.0 as reported by @rouault in #10055. Personally I wouldn't have opened a new bug as to me it is part of the breakage introduced by 2024.06.03.1.0 so covered here. Surprisingly the test of my project's Python binding now works. Surprising because the first `vcruntime140.dll` in `$env:PATH` is still the old one in `C:\hostedtoolcache\windows\Python\3.9.13\x64\vcruntime140.dll`. I will have to check if my Python binding test is exercising any of the multithreaded code in the underlying library.

FWIW, I don't have Java bindings in my project, but I do have Python bindings (using `pybind11`) and my Python-related tests still fail on Windows while everything is back to normal when it comes to my C++-related tests.

**Comment by mprather** [comment]
Just adding some info -- our C++ tests are still failing even with the new 610 hosted image. We rely on dlls created with an older runtime. We've never had an issue building and then running new tools that rely on these 3rd party dlls, until the new hosted image arrived.

**Comment by MarkCallow** [comment]
I encountered a new problem in 2024.06.10.1.0. Previously this line in the `jobs.env:` section

```
CMAKE_GEN: ${{ matrix.generator }}
```

resulted in the environment variable not being set if `matrix.generator` was not set. In 2024.06.10.1.0 it results in CMAKE_GEN being set to an empty string. Our build script sets a default generator if CMAKE_GEN is not set. As the variable is set, the default isn't set and CMake config fails. I fixed this by setting `generator` in every part of the matrix.

**Comment by MarkCallow** [comment]
> FWIW, I don't have Java bindings in my project, but I do have Python bindings (using `pybind11`) and my Python-related tests still fail on Windows while everything is back to normal when it comes to my C++-related tests.

Thanks. Probably our Python test is not exercising any multi-threaded code in the underlying library.

**Comment by MarkCallow** [comment]
> > FWIW, I don't have Java bindings in my project, but I do have Python bindings (using `pybind11`) and my Python-related tests still fail on Windows while everything is back to normal when it comes to my C++-related tests.
> 
> Thanks. Probably our Python test is not exercising any multi-threaded code in the underlying library.

Our test _is_ exercising multi-threaded code. I do not know why your tests still fail in 2024.06.10.1.0 @agarny while mine work.

**Comment by agarny** [comment]
> Our test _is_ exercising multi-threaded code. I do not know why your tests still fail in 2024.06.10.1.0 @agarny while mine work.

I have just had a look at my [Python-related test](https://github.com/opencor/libopencor/actions/runs/9478653324/job/26156198579) and most of it is fine and it's not related to the multi-threaded aspect of this issue. My test fails when trying to build my project using `pip install .` which is done using `skbuild` and, for some reasons, it's [not able to copy a file](https://github.com/opencor/libopencor/actions/runs/9478653324/job/26156198579#step:35:332). Anyway, all I know is that it all used to work fine before 2024.06.03.1.0. So, I am going to wait for this issue to be considered fixed before concluding anything.

**Comment by ijunaidm** [comment]
@llvm-beanz - Does your issue got fixed, as we did the image deployment. If your facing same issue ,kindly let us know.

**Comment by pattacini** [comment]
I had a problem similar to the OP on my CI and now it's fixed after the latest deployment.
Thanks!

**Comment by snnn** [comment]
Run this script:
```
Get-ChildItem -Path "C:\hostedtoolcache\windows" -File -Include msvcp*.dll,concrt*.dll,vccorlib*.dll,vcruntime*.dll -Recurse | Remove-Item -Force -Verbose
```

**Comment by torokati44** [comment]
> You don't have a reason not running it.

The fact that it takes over 15 minutes does count as a reason to me: https://github.com/ruffle-rs/ruffle/actions/runs/9512755132/job/26221430721?pr=16713
And it doesn't fix the problem.

**Comment by lelegard** [comment]
Bad news, the last updated runner does not fully work. Specifically, Java applications using JNI (Java Native Interface) still fail. The DLL which is called in the Java application is built and tested in the runner. Reverting to the `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` trick makes the applications work again, Java included.

See https://github.com/actions/runner-images/issues/10020#issuecomment-2168449045

Interestingly, Python applications do not fail when calling the same DLL (the project has Java and Python bindings).

**Comment by snnn** [comment]
> Java applications using JNI (Java Native Interface) still fail

Run the following command will solve the issue:

``` Powershell
Get-ChildItem -Path "C:\hostedtoolcache\windows" -File -Include msvcp*.dll,concrt*.dll,vccorlib*.dll,vcruntime*.dll -Recurse | Remove-Item -Force -Verbose
```

**Comment by snnn** [comment]
> Python applications do not fail 

 Because python.exe is written in pure C. The ABI change in VS 2022 17.10 is for C++.

**Comment by lelegard** [comment]
@snnn 
> Run the following command will solve the issue:
> `Get-ChildItem -Path "C:\hostedtoolcache\windows" -File -Include msvcp*.dll,concrt*.dll,vccorlib*.dll,vcruntime*.dll -Recurse | Remove-Item -Force -Verbose`

Running this command takes 28 minutes 51 seconds to find and delete 38 files. It is not an acceptable solution to run before each CI job. Another user reported it took 15 minutes and did not solve the issue. So, no, sorry.

**Comment by snnn** [comment]
@lelegard , it depends on how you got the Java runtime. If the java.exe that was used for running the tests in your pipelines was in the `C:\hostedtoolcache\windows` folder, then the command above can solve the issue.

**Comment by lelegard** [comment]
@snnn 
> it depends on how you got the Java runtime. If the java.exe that was used for running the tests in your pipelines was in the C:\hostedtoolcache\windows folder,

Continuous integration needs a reproducible build, especially for Java where so many versions exist. The workflow downloads and install all its pre-requisites. Java comes from `adoptium.net`, the de-facto standard for Java deployment on Windows nowadays.

All CI tests pass on local Windows machines, as used by maintainers and contributors. It used to work on the CI until the infamous update of last week. It no longer works in the CI runner, even after today's "fix". So, the CI runner remains broken and must be fixed.

**Comment by agarny** [comment]
FWIW, I don't know whether the `20240610.1.0` runner image is considered to be fine (probably not since this issue is still open!), but just in case it's still broken for me. I have a C++ project with some Python bindings and one of the steps in my Windows CI is to `pip install .` using `scikit-build`. It all used to work fine before the `20240603.1.0` runner image, but now it's broken (while it's fine on Linux and macOS). So, for the GitHub devs, you might want to check [this](https://github.com/opencor/libopencor/commit/e1336b80d59f88f6e10b7a7ecaa812ce5eecb48c#diff-030d3f331421c38bcfff91c9bb089199ec541ba051f2a2723ca40db4dc98b737R55-R67) which is my hack (!!) to get the `20240610.1.0` runner image to work for my needs since I really need and want my Windows jobs back.

**Comment by kishorekumar-anchala** [comment]
HI @llvm-beanz ,

 we hope you're issue got resolved after deploying the latest version , Please share your comments on it .

**Comment by llvm-beanz** [comment]
@kishorekumar-anchala, the latest image seems to work for us.

There has to be a better way to resolve issues like this more quickly. This was an _enormous_ disruption to our team and teams across the world.

Do you have some sort of RCA that you've performed which captures how you can prevent issues like this in the future and/or respond more quickly to them if the occur?

**Comment by PeterJohnson** [comment]
For those interested in seeing the root cause (the unversioned MSVC runtime causing UB crashes instead of a noisy but explanatory at-startup failure) fixed, upvote my “reconsider” comment here: https://developercommunity.visualstudio.com/t/Access-violation-in-_Thrd_yield-after-up/10664660#T-N10669129-N10678728

**Comment by mprather** [comment]
> @kishorekumar-anchala, the latest image seems to work for us.
> 
> There has to be a better way to resolve issues like this more quickly. This was an _enormous_ disruption to our team and teams across the world.
> 
> Do you have some sort of RCA that you've performed which captures how you can prevent issues like this in the future and/or respond more quickly to them if the occur?

@kishorekumar-anchala: I concur with @llvm-beanz's RCA proposal. The number of man hours spent on investigations is astonishing. We poured through every commit and reran everything piece by piece. Only to come the resolution that it wasn't our fault. This cost us 3 days before finding this specific ticket that offered some insight. Couple that with inability to run tests for days on end before some resolution was on the horizon -> this was a very expensive break and disrupted delivery schedules. Now fold in everyone else that scrambled in a similar fashion. And for some, the image is still effectively broken and still running up the tab.

I have never considered Azure hosted images to be unreliable until now. There was no communication that an image was being updated in a substantial form. No real way to figure out if the issue was known or being addressed. 

This lack of communication also bit our team the week prior when we learned (via series of failed tests) that gcc 13 had been pulled off a set of images without any meaningful announcements.  Some might argue that the gcc changes might be posted via tasks in the runner repos but I don't monitor them. Instead, I always reference a page such as [Microsoft-hosted agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) to understand the current config opportunities and scan the updates list. I've never seen images degrade in tooling and stability as they have in the past few weeks. Please consider how to inform customers more effectively as well as responding more efficiently.

**Comment by agarny** [comment]
Like others, I really wish there was more and better communication from the team. The `20240610.1.0` runner image still doesn't work for my project (see [above](https://github.com/actions/runner-images/issues/10004#issuecomment-2172690577)) and [`nanobind`](https://github.com/wjakob/nanobind) (see [here](https://github.com/wjakob/nanobind/issues/613)), which I want to be able to use.

**Comment by ijunaidm** [comment]
@llvm-beanz -
We are closing this issue, as your builds were failing are now successful after the 20240610 image deployment and are fixed.

https://dev.azure.com/DirectXShaderCompiler/public/_build/results?buildId=6395&view=results
https://dev.azure.com/DirectXShaderCompiler/public/_build?definitionId=1&_a=summary

Thank you. Kindly reach out to us if you still face any new issues.

**Comment by BrianMouncer** [comment]
> @llvm-beanz - We are closing this issue, as your builds were failing are now successful after the 20240610 image deployment and are fixed.
> 
> https://dev.azure.com/DirectXShaderCompiler/public/_build/results?buildId=6395&view=results https://dev.azure.com/DirectXShaderCompiler/public/_build?definitionId=1&_a=summary
> 
> Thank you. Kindly reach out to us if you still face any new issues.

@ijunaidm Do you have more information on this change.  In our case, JVM itself is loading an older version of vc runtime from it's deployed folder, so even if we remove or update the vc dlls in system32 and other paths on the agent image, JVM still loads an older version of the runtime before we are even called, so our native code will crash on load if we build on the latest 20240610.

The 20240610 image in un-usable to us, unless we modify our code, and work with all our partner team to have them also start building with the  D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR flag defined.

This does not seem like a good path forward.  How long will the D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR be supported? What other std incompatibilities are in there that we do not know about yet, and are not covered by this one compiler flag?

Do you know if there is a customer impact issue for this in the DevDiv team?

**Comment by BrianMouncer** [comment]
> > @kishorekumar-anchala, the latest image seems to work for us.
> > There has to be a better way to resolve issues like this more quickly. This was an _enormous_ disruption to our team and teams across the world.
> > Do you have some sort of RCA that you've performed which captures how you can prevent issues like this in the future and/or respond more quickly to them if the occur?
> 
> @kishorekumar-anchala: I concur with @llvm-beanz's RCA proposal. The number of man hours spent on investigations is astonishing. We poured through every commit and reran everything piece by piece. Only to come the resolution that it wasn't our fault. This cost us 3 days before finding this specific ticket that offered some insight. Couple that with inability to run tests for days on end before some resolution was on the horizon -> this was a very expensive break and disrupted delivery schedules. Now fold in everyone else that scrambled in a similar fashion. And for some, the image is still effectively broken and still running up the tab.
> 
> I have never considered Azure hosted images to be unreliable until now. There was no communication that an image was being updated in a substantial form. No real way to figure out if the issue was known or being addressed.
> 
> This lack of communication also bit our team the week prior when we learned (via series of failed tests) that gcc 13 had been pulled off a set of images without any meaningful announcements. Some might argue that the gcc changes might be posted via tasks in the runner repos but I don't monitor them. Instead, I always reference a page such as [Microsoft-hosted agents](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml) to understand the current config opportunities and scan the updates list. I've never seen images degrade in tooling and stability as they have in the past few weeks. Please consider how to inform customers more effectively as well as responding more efficiently.

Initially I don't think this in on the hosted image maintainers.  My point of view is that this is a failure on the Visual Studio team that allowed such a change to ship in the first place.  The only area the hosted image folks could have improved would be to have rolled back the compiler upgrade as soon as they realized what happened, and to then message it to the community and push back on the Compiler team to unbreak the STD classes in the vc runtime.... or at a bare minimum published a high visibility  breaking change message as soon as they root caused the issue?

**Comment by MarkCallow** [comment]
> In our case, JVM itself is loading an older version of vc runtime

@BrianMouncer #10020 and #10055  also cover the JVM issues.

**Comment by MarkCallow** [comment]
> Initially I don't think this in on the hosted image maintainers.

It is. They deployed an image in which the VC runtime installed in `C:\Windows\system32` did not match the version of the image's compiler,  so all tests running newly compiled code failed. They also, as you said, should have rolled back the image as soon as the magnitude of the issue became apparent. 

As for MS, they need to fix the compiler tool chain so that the dynamic linker ensures code is linking to a compatible version of the runtime and fails with an understandable error message when the versions mismatch.

**Comment by mprather** [comment]
> Initially I don't think this in on the hosted image maintainers. 

@BrianMouncer It's a maintainer's issue. I have no gripes with the VC team, as a matter of fact.  The images were improperly built. As supporting evidence, we re-ran pipelines that had previously succeeded with May's image and found those pipelines failed with the new June image. Then that same code started working again when the `20240603.1.0` image was deployed. That is not a code issue and certainly not a runtime issue. It's an image configuration issue. 

We lucked out that our 3rd party libraries started working with the fix. We never had to touch our code b/c it never explicitly dealt with mutex issue. So, yes, magically on the 13th of the month, everything started working for us with no code change. It's an image issue. The sticky part is the issue still exists for some - #10020 is still active and very much a concern for a lot of folks since the new configuration is still a blocking issue for them.

It's worth noting that the reason I also called out the gcc issue was to illustrate that two different platforms suffered from the lack of clear communication, and both practically happened at the same time. That's a lot of expensive deviations due to debugging, workarounds, etc. The windows issue illustrates a need for better testing, monitoring, and response. The ubuntu issues took an image set backwards. Both issues highlight a lack of communication. We spent a lot of time (man hours and pipeline time) on issues that really shouldn't have happened in the first place (windows c++ issue) or, at the very least, with sufficient notice to allow for planned changes (ubuntu issue).

**Comment by MarkCallow** [comment]
Is the  `#define _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` workaround needed with clangcl as well as msvc?.

**Comment by MarkCallow** [comment]
> Is the `#define _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR` workaround needed with clangcl as well as msvc?.

I found my own answer after looking back at CI build logs. Usually an msvc build failed first cancelling the other builds but I found an occurrence where the runner image was updated after the msvc jobs had completed but before a clangcl jobs. It suffered crashes and SEH exceptions in the way familar to everyone here. The workaround is needed also with ClangCL..
