### ISSUE TITLE
sudo: apt-fast: command not found

### ISSUE THREAD

**Issue by Krinkle** [actions/runner-images#10003]
### Description

The `apt-fast` command has seemingly been removed without notice.

I was unable to find why or how. I did find https://github.com/actions/runner-images/pull/9952 which describes it after the fact, but I could not find when/how/why it was removed.

> As we fixed apt-fast's installation condition on Ubuntu 24.04, it is no longer being installed

Suffice to say, it is not a fix from my perspective :)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Before - main branch passes until 4 days ago at https://github.com/qunitjs/qunit/actions/runs/9342054787/job/25709566600

```
Current runner version: '2.316.1'
Runner Image
  Image: ubuntu-24.04
  Version: 20240516.4.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20240516.4/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240516.4
Runner Image Provisioner
  2.0.370.1
```

After - Failing as of today at https://github.com/qunitjs/qunit/actions/runs/9403484460/job/25900141520

```
Current runner version: '2.317.0'
Runner Image
  Image: ubuntu-24.04
  Version: 20240604.1.0
  Included Software: https://github.com/actions/runner-images/blob/ubuntu24/20240604.1/images/ubuntu/Ubuntu2404-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/ubuntu24%2F20240604.1
Runner Image Provisioner
  2.0.370.1
```

### Is it regression?

yes

### Expected behavior

apt-fast installed.

### Actual behavior

apt-fast suddenly not installed anymore.

### Repro steps

1. `runs-on: ubuntu-24.04`
2. `run: sudo apt-fast install -y libmozjs-102-dev`

**Comment by hemanthmanga** [comment]
@Krinkle We are looking into the issue, we will get back to you after investigating this issue.

**Comment by mikhailkoliada** [comment]
Hey! There are no plans to add apt-fast to ubuntu24, it was installed by mistake and now this was fixed, it is expected.

**Comment by Krinkle** [comment]
@mikhailkoliada Thanks for confirming the intention. Would you be able to share the reason this was seen as a mistake? On the surface, it seems the apt-fast project still exists and describes itself as an improvement. It shipped for many years here with Ubuntu 20 and 22 (and still does). It's not obvious why its use in GitHub Actions is seen as a mistake after Ubuntu 24. I'm asking so that others in the community can make informed choices based on what you found/learned.

For example, did you find that upstream apt-get improved in Ubuntu 24 such that apt-fast no longer made a measurable speed difference? Or do you have custom list of local mirrors that make apt-fast and apt-get equally fast in the common case (for non-PPA apt sources), and so it was never useful in this context in the first place? Something else?
