### ISSUE TITLE
First run of az-cli is slow 

### ISSUE THREAD

**Issue by lanni-energinet** [actions/runner-images#10110]
### Description

For quite some time we have been impacted by poor performance due to the nature of az-cli's command and module caching on it's first run. It would seem that az-cli was not written with ephemeral runners in mind, and it doesn't look like they could change this easily. Hence why we are opening this issue here.

We can see that the issue is fixed on windows images as a simple warmup has been implemented
https://github.com/actions/runner-images/blob/c5c9a7cd7b2cfd20d740f7667fdaca8a412f2b52/images/windows/scripts/build/Install-AzureCli.ps1#L22

Can you please implement a simple warm up like on the windows runners?

From a sample of our logs we have measured the following impact
Minimum 2 s
Maximum 31 s
Average 5 s

We estimate wasting roughly 6500 minutes per month which is more than 10% of our of total usage

### Platforms affected

- [x] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [X] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20240609.1

### Is it regression?

no

### Expected behavior

A build-in warmup in the ubuntu image creation similar to the windows image

### Actual behavior

No warmup

### Repro steps

None needed

**Comment by kishorekumar-anchala** [comment]
HI @lanni-energinet , 

 Thank you for bringing this issue to us, we are investigating on this issue and we will update you on this issue after our findings.

**Comment by RaviAkshintala** [comment]
@lanni-energinet 


Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by lanni-energinet** [comment]
@kishorekumar-anchala 

i've attached a proposed implementation on the PR can you take a look
https://github.com/actions/runner-images/pull/10126#issuecomment-2262893593

**Comment by lanni-energinet** [comment]
@kishorekumar-anchala 

Can we in any way assist in the resolution of this issue. We are wasting a lot of time and money on this

**Comment by j15e** [comment]
Not sure if the proposed fix would fix our issue, but when we run the login action on Ubuntu, it sometimes takes up to **2 minutes** to simply run the first clear command like this, which is insanely long for such a basic task:

![image](https://github.com/user-attachments/assets/a064d28c-863e-4021-bf01-c9c36e48374e)

**Comment by kishorekumar-anchala** [comment]
@lanni-energinet , We are considering your workflow and doing changes . we're facing the some issue , we'll get back to you Asap. THANK YOU !

**Comment by lanni-energinet** [comment]
@kishorekumar-anchala Any progress to report?

**Comment by illrill** [comment]
Feeling this pain too. Basically every one of our jobs begin with running `azure/login@v2`, which annoyingly always takes between 10 and 30 seconds.

**Comment by kishorekumar-anchala** [comment]
HI @lanni-energinet ,

By implementing this we're getting permission error .   it would be helpful if you provide repro steps . thank you for your support !
```
==> azure-arm.build_image:     with open(self.config_path, 'w', encoding=CONFIG_FILE_ENCODING) as configfile:
==> azure-arm.build_image:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
==> azure-arm.build_image: PermissionError: [Errno 13] Permission denied: '/home/root/.azure/config'
==> azure-arm.build_image: ToolVersionNode 'Azure CLI' has empty version
==> azure-arm.build_image: At /imagegeneration/SoftwareReport/software-report-base/SoftwareReport.Nodes.psm1:166 char:13
==> azure-arm.build_image: +             throw "ToolVersionNode '$($this.ToolName)' has empty vers …
==> azure-arm.build_image: +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.build_image: + CategoryInfo          : OperationStopped: (ToolVersionNode 'Az…' has empty version:String) [], RuntimeException
==> azure-arm.build_image: + FullyQualifiedErrorId : ToolVersionNode 'Azure CLI' has empty version
```

**Comment by lanni-energinet** [comment]
@kishorekumar-anchala

Can you test this PR: https://github.com/actions/runner-images/pull/11173

**Comment by lanni-energinet** [comment]
@kishorekumar-anchala 

Sorry about that. I overlooked that the install scripts was running as `root`, but the tests was running as `packer`.

I've updated the PR and tests are now passing.

**Comment by kishorekumar-anchala** [comment]
Hi @lanni-energinet - I tested the changes ,  working good .  Thanks you for your support in implementing the request. PR will be in review. I will update you once it merged .

**Comment by chrisjohnson00** [comment]
@subir0071 Can this please be re-opened.  The [PR referenced](https://github.com/actions/runner-images/pull/11173), which fixed the issue, was reverted, so this issue remains.

**Comment by erik-bershel** [comment]
The solution will not be implemented. Tampering with the configuration disrupts users.

**Comment by chrisjohnson00** [comment]
> The solution will not be implemented. Tampering with the configuration disrupts users.

I may not fully understand [the PR](https://github.com/actions/runner-images/pull/11173), but it looked to me like the proposed solution included the fix to pre-warm the CLI, but also added some environment changes.  From my limited understanding, I thought the pre-warming part could be done without environment changes, am I misunderstanding?

I was hoping the solution was as simple as running `az help`, or other more appropriate command, as a post CLI install step.

**Comment by erik-bershel** [comment]
> I was hoping the solution was as simple as running az help, or other more appropriate command, as a post CLI install step.

Unfortunately, things aren't that simple. The image undergoes mandatory generalization after generation, which destroys some data and configurations, including resetting the `az cli` to its default state. A workaround requires reconfiguring the utility's environment, which in turn breaks certain use cases and dependent processes.

**Comment by lanni-energinet** [comment]
@chrisjohnson00 

The underlying issue has been identified a while ago.

https://github.com/Azure/azure-cli/issues/31541

**Comment by chrisjohnson00** [comment]
> @chrisjohnson00 
> 
> The underlying issue has been identified a while ago.
> 
> https://github.com/Azure/azure-cli/issues/31541
> 
> 

Hmpf, reads like a classic msft problem. Imagine if you couldn't pre pull containers because the runner user doesn't exist yet?

The devil on one shoulder says this isn't prioritized because it makes github and msft money.  I'm about to try the new byo image on github runners, just to pre warm. That new feature requires the larger runners, so now I have to do cost analysis and change dozens of workflows, assuming it works.

Thanks for rehashing the issues... I hope cli can figure out something, but I won't hold my breath.

**Comment by MoChilia** [comment]
>  The image undergoes mandatory generalization after generation, which destroys some data and configurations, including resetting the az cli to its default state.

@erik-bershel, I’d like to run `az --help` to warm up the CLI without modifying any environment variables, right after installing azure-cli. By default, if `AZURE_CONFIG_DIR` and `AZURE_EXTENSION_DIR` are unset, they use `$HOME/.azure` and `$HOME/.azure/cliextensions`.

Are you saying that the mandatory generalization of the image might clear or overwrite cache in the default `$HOME` directory? Is there a way to preserve this cache?

@lanni-energinet, could you please reopen this issue? I think it’s a good topic that worth further discussion.

**Comment by erik-bershel** [comment]
Hey @MoChilia! 👋 

The user used during the build and the user used when running the agent are different entities. Confirm that the tool warm-up will work as expected after the changes you made on the tool side, and we will be happy to get back to issue.

**Comment by MoChilia** [comment]
Hi @erik-bershel, could you help me understand the difference between "during the build" and "when running the agent"? I’d like to focus on the scenario where a user runs a workflow with `runs-on: ubuntu-latest`, as this is the most common case for using Azure CLI in GitHub Actions.

<img width="1246" height="242" alt="Image" src="https://github.com/user-attachments/assets/a483e73d-fc2e-41d7-b3a5-3b50534de43e" />

My understanding is that if we warm up Azure CLI during the image build step, subsequent Azure CLI commands in the workflow can utilize the generated cache, avoiding the initial slow run.

What changes would be required on the Azure CLI side to support this? Both the Azure/login and Azure/cli action are already set to benefit from cached command index in `AZURE_CONFIG_DIR`. I’m happy to collaborate with you to implement this improvement.

**Comment by erik-bershel** [comment]
@MoChilia 

Let's briefly summarize. What does the generation process look like in the section we're discussing?

- A virtual machine is created
- A user is created on the virtual machine, let's call it `Packer`
- Installation scripts are executed as this user
- The `Packer` user is deleted
- A new user is created, let's call it `Runner`
- Further work is performed under this user

Info: https://learn.microsoft.com/en-us/azure/virtual-machines/generalize
 
---

To ensure that warmup during build is transferred to the runner and is available when using any of the `ubuntu-xx.04` images, Azure CLI must not be tied to the user environment, but rather store all settings, files, and caches in its own or one of the system directories.

**Comment by lanni-energinet** [comment]
@MoChilia 

I am unable to reopen this issue due to permissions.

It's documented and reproducible that the issue is related to commandindex.json generation, I'm fully aware that the slow generation could be caused by externals related to github runners.

But I'm perplexed to the hesitance from Azure CLI / Knack team to investigate the real issue, can you give any insights into this?

**Comment by MoChilia** [comment]
@erik-bershel, thank you for the clear explanation. I understand now. Since Azure CLI extensions are installed per user, Azure CLI must generate the command index individually for each user by loading all the main modules and installed extensions. We can't cache the command index in system directories, as changing this behavior could introduce breaking changes.

@lanni-energinet, some delay in generating the command index is inevitable, but the unpredictable duration seems to be machine-related. I'll look into this further.

**Comment by chrisjohnson00** [comment]
Likely an unpopular opinion... but why not just create the `runner` user in Packer, then run `az version` as this user to warm up the CLI?

>The sudo waagent -force -deprovision+user command generalizes the image by attempting to clean the system and make it suitable for reprovisioning. The +user option deletes the last provisioned user account and associated data.

Not sure [if this](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-ubuntu) would remove the `runner` user or just the `packer` user though?

**Comment by erik-bershel** [comment]
>Likely an unpopular opinion... but why not just create the runner user in Packer, then run az version as this user to warm up the CLI?

> Not sure [if this](https://learn.microsoft.com/en-us/azure/virtual-machines/linux/create-upload-ubuntu) would remove the runner user or just the packer user though?


The build and deployment process is designed in such a way that both users will be deleted regardless. There are specific reasons for this that are technically difficult to overcome at the moment, but discussions are ongoing, as a warmed-up user is a very useful feature for the community.

Unfortunately, we haven't yet found a technically suitable solution. The main problem lies at the interface between platforms and is external to us. 😞
