### ISSUE TITLE
Dotnet Publish crashes with error 'MSB4166: Child node "##" exited prematurely. Shutting down.'

### ISSUE THREAD

**Issue by lancelind** [actions/runner-images#10437]
### Description

Starting with release 2.319.0 we are consistently seeing the following process crash when running dotnet publish.

MSBUILD : error MSB4166: Child node "xx" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTemprunner/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: /tmp/MSBuildTemprunner/MSBuild_pid-3214_c9915635ac784de6a0cbd7762603f60a.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 3214:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 08/13/2024 17:39:05
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166: 
MSBUILD : error MSB4166: 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Image version 2.319.0. 

### Is it regression?

Yes.  2.318.0 did not have this version.

### Expected behavior

Successful completion of dotnet publish

### Actual behavior

dotnet.exe process crash

### Repro steps

- Install 2.319.0 on our runners
- With a dotnet 8.0 project, run dotnet publish

**Comment by bgrainger** [comment]
We're getting this exception on some of our self-hosted runners, but not all. It seems to only happen with SDK 8.0.400 but not 8.0.304; try using a `global.json` to explicitly use the older SDK:

```json
{
  "sdk": {
    "version": "8.0.304"
  }
}
```

(That is, I suspect it's an issue in the SDK, not in https://github.com/actions/runner.)

**Comment by bgrainger** [comment]
Since this appears to be happening from telemetry, try setting the `DOTNET_CLI_TELEMETRY_OPTOUT` environment variable to `1`.

**Comment by joacar** [comment]
This happens in Azure Devops with self-hosted agents as well. Agent version 2.206.1 running Linux

**Comment by jculverwell** [comment]
Getting the same issue, looks like something broke today.  Github action is failing whilst building a .net 8.0 C# project....


MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in "/tmp/MSBuildTemprunner/" and will be named MSBuild_*.failure.txt. This location can be changed by setting the MSBUILDDEBUGPATH environment variable to a different directory.
MSBUILD : error MSB4166: /tmp/MSBuildTemprunner/MSBuild_pid-2168_97623965aa194746ac7549b455b[865](https://github.com/xxxxxxxx/xxxxxxx/actions/runs/10381140779/job/28747006362#step:5:866)73.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 2168:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 08/14/2024 07:07:10
MSBUILD : error MSB4166: System.ArgumentNullException: Value cannot be null. (Parameter 'value')
MSBUILD : error MSB4166:    at System.ArgumentNullException.Throw(String paramName)
MSBUILD : error MSB4166:    at System.IO.BinaryWriter.Write(String value)
MSBUILD : error MSB4166:    at Microsoft.Build.Framework.TelemetryEventArgs.WriteToStream(BinaryWriter writer)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.WriteToStream(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Shared.LogMessagePacketBase.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166: 
MSBUILD : error MSB4166: 
Error: Process completed with exit code 1.

**Comment by jculverwell** [comment]
Can also confirm that adding the ENV variable (DOTNET_CLI_TELEMETRY_OPTOUT: 1) to the github action fixed the issue

**Comment by baronfel** [comment]
This is a dotnet SDK regression - we will have a 401 hotfix SDK out in the next day or so that fixes this. In the meantime the most consistent workaround is using the latest 30x SDK instead.

**Comment by bgrainger** [comment]
Duplicate issues filed:

* https://github.com/dotnet/msbuild/issues/10518
* https://github.com/dotnet/sdk/issues/42719
* https://github.com/dotnet/sdk-container-builds/issues/587

**Comment by onionhammer** [comment]
This started happening for me as well

**Comment by baronfel** [comment]
The [8.0.401](https://dotnet.microsoft.com/en-us/download/dotnet/8.0) hotfix SDK has been released on all channels and contains a fix for this issue.

**Comment by ivan-84** [comment]
Apparently the same regression has been introduced in .NET 9 preview (9.0.100-preview.7.24407.12) which is now installed with the latest VS, because even after installing 8.0.401 whenever I'm trying to run `azd deploy MyService` it fails with the error above. When running `azd deploy` with `--debug` flag I can see that it appears to be using the latest available .NET version which in my case is the .NET 9 preview. The only way how I could make it work (setting `DOTNET_CLI_TELEMETRY_OPTOUT` to 1 did nothing) is to add in the root folder of my solution "global.json" with this content:
```
{
    "sdk": {
        "version": "8.0.401"
    }
}
```

**Comment by hemanthmanga** [comment]
Hi @lancelind, Could you please confirm if the issue is fixed as external team SDK have provided workarounds Like below :

try using a global.json to explicitly use the older SDK:

```
{
  "sdk": {
    "version": "8.0.304"
  }
}
```
(That is, I suspect it's an issue in the SDK, not in https://github.com/actions/runner.)

Thank you.

**Comment by joacar** [comment]
It resolves the issue!

Skickat från min iPhone


tors 29 aug. 2024 kl. 12:26 skrev hemanthmanga ***@***.***>:

**Comment by hemanthmanga** [comment]
Hi @lancelind, Since we haven't heard back, we'll assume your issue is resolved and will close this issue, Thanks.

**Comment by Kralizek** [comment]
I'm having this issue since yesterday (not sure what changed on my machine behind the scenes) and only on some projects but not all of them. Enabling telemetry fixes the issue. 

```
$ dotnet --info # failing project

.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.57f7c351
 MSBuild version:   17.11.3+0c8610977

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400, VS 17.11.35222.181
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  6.0.425 [C:\Program Files\dotnet\sdk]
  8.0.304 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Users\rg1844\Development\TobiiDynavox\IdentityManager\App\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

```
$ dotnet --info # succeeding project

.NET SDK:
 Version:           8.0.400
 Commit:            36fe6dda56
 Workload version:  8.0.400-manifests.57f7c351
 MSBuild version:   17.11.3+0c8610977

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.400\

.NET workloads installed:
Configured to use loose manifests when installing new manifests.
 [aspire]
   Installation Source: SDK 8.0.400, VS 17.11.35222.181
   Manifest Version:    8.2.0/8.0.100
   Manifest Path:       C:\Program Files\dotnet\sdk-manifests\8.0.100\microsoft.net.sdk.aspire\8.2.0\WorkloadManifest.json
   Install Type:        FileBased


Host:
  Version:      8.0.8
  Architecture: x64
  Commit:       08338fcaa5

.NET SDKs installed:
  6.0.425 [C:\Program Files\dotnet\sdk]
  8.0.304 [C:\Program Files\dotnet\sdk]
  8.0.400 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.25 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

As you can see, the only difference is the presence of the global.json file in the broken project.

```
{
  "sdk": {
    "version": "8.0.200",
    "rollForward": "latestMinor"
  }
}
```

**Comment by idigra** [comment]
@hemanthmanga I still see the issue sporadically on various version of .NET 8 (I'm on latest 403 and tried to reduce to 304 - reproduced on both).
