### ISSUE TITLE
Wrong Signature Thumbprint - Install Visual Studio - Windows Server 2022 Runner Image 

### ISSUE THREAD

**Issue by Ami-007** [actions/runner-images#10561]
### Description

Install Visual Studio has the wrong signature thumbprint on the test.

==> azure-arm.build_vhd: Provisioning with powershell script: /agent/_work/1/s/runner-images/images/windows/scripts/build/Install-VisualStudio.ps1
    azure-arm.build_vhd: Downloading Bootstrapper ...
    azure-arm.build_vhd: Downloading package from https://aka.ms/vs/17/release/vs_Enterprise.exe to C:\Users\INSTAL~1\AppData\Local\Temp\vs_Enterprise.exe...
    azure-arm.build_vhd: Package downloaded in 0.42 seconds
    azure-arm.build_vhd: Signature thumbprint do not match expected.
    azure-arm.build_vhd: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:973 char:9
    azure-arm.build_vhd: +         throw "Signature thumbprint do not match expected."
    azure-arm.build_vhd: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    azure-arm.build_vhd:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
    azure-arm.build_vhd:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
    azure-arm.build_vhd:

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

N/A private build

### Is it regression?

Yes - this worked on 19th August 2024

### Expected behavior

All tests pass successfully and build completes successfully for Windows 2022 using the build code in runner images repo

### Actual behavior

Our pipeline that builds the Windows 2022 image using the runner-images code from this repo is failing when attempting to install Visual Studio Enterprise and producing thumbprint error.

### Repro steps

Run Packer build using the latest code in this repo for Windows Server 2022

**Comment by RaviAkshintala** [comment]
@Ami-007 Thank you for bringing this issue to us. We are looking into this issue and will update you on this issue after investigating.

**Comment by angaaruriakhil** [comment]
I am also having this issue. I see this issue frequently with this repository. Is there no way to have this automated in some way instead of doing manual fixes?

**Comment by vidyasagarnimmagaddi** [comment]
Hi @cupacheeno , the new image has been rolled out (20240912.1.1) .The issue is fixed now. kindly synch your main .Thanks

**Comment by Ami-007** [comment]
> Hi @cupacheeno , the new image has been rolled out (20240912.1.1) .The issue is fixed now. kindly synch your main .Thanks

Where has 22 been fixed? I see a code update for 2019, but not for 2022. I have run a build and am still seeing the same error

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Ami-007  , Please follow the official status page of Azure DevOps for updates https://status.dev.azure.com/_event/543117809

**Comment by Ami-007** [comment]
> Hi @Ami-007 , Please follow the official status page of Azure DevOps for updates https://status.dev.azure.com/_event/543117809

What does that have to do with the price of eggs?

I’m telling you that you haven’t updated the VS signature for Windows 2022 builds. Which incidentally, is what this issue is about.

**Comment by cupacheeno** [comment]
@vidyasagarnimmagaddi can confirm in our instance the runners now work as expected

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Ami-007  , the visual studio signature thumbprint is already with the latest one,  windows-2022 is successful.
The thumbprint we are using is this `F9A7CF9FBE13BAC767F4781061332DA6E8B4E0EE`.Kindly check the same. thanks

**Comment by vidyasagarnimmagaddi** [comment]
Hi @Ami-007 , the new image version 20240915.1 is rolled out. And we see no issue with visual studio signature thumbprint. Kindly synch your main . Closing the issue. Thanks.

**Comment by hmayer1980** [comment]
I still have this issue on main - and I did try "releases/win22/20241021" where I also have this issue!
