### ISSUE TITLE
Linux user changing between versions

### ISSUE THREAD

**Issue by williamho123** [actions/runner-images#12194]
### Description

When using `actions/cache@v4` to restore a cache on disk, the `tar` command is erroring out with messages like:
```
/usr/bin/tar: ../../../../../opt/hostedtoolcache/Python/3.10.17/x64/bin: Cannot utime: Operation not permitted
/usr/bin/tar: ../../../../../opt/hostedtoolcache/Python/3.10.17/x64/bin: Cannot change mode to rwxr-xr-x: Operation not permitted
```

Upon further inspection, it appears that the Action is executing as the `runner` user but the owner of the directory in question is `packer`. This is leading to the permissions issues.

Is this new behavior expected? Previous versions of the runner restored cache successfully.

Also, this appears to affect Ubuntu 24.04 runner image version `20250427.1.0` but we don't see the issue on the newer `20250504.1.0`. In the same repository, we were using the newer image version up until today, when for some reason, the Github hosted runners started using the older version.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [x] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [ ] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

20250427.1.0

### Is it regression?

Yes - 20250504.1.0

### Expected behavior

The cache restore to work successfully, and the owner of the directory to be the same user as the one executing the Action (`runner`).

### Actual behavior

The cache restore fails with permissions errors from `tar`.

### Repro steps

1. Setup a workflow that sets up Python 3.10 with `actions/setup-python@v5`.
2. Also use the cache action to cache the Python install: `actions/cache@v4`
3. Run the workflow for the first time. It will succeed because it is an empty cache.
4. Run the workflow again. The cache restore will fail if runner image is version `20250427.1.0` (I'm not sure how to reliably select the version here).

Example:
```yaml
- name: Setup Python
  id: setup-python
  uses: actions/setup-python@v5
  with:
    python-version: 3.10

- name: Cache
  uses: actions/cache@v4
  id: cache
  with:
    path: ${{ env.pythonLocation }}
    key: <replace-with-my-cache-key>
```

**Comment by williamho123** [comment]
Forgot to post screenshots of the different users and versions

### Successful version

![Image](https://github.com/user-attachments/assets/c4967578-f3e3-45a9-8de6-f77fab21e87a)
![Image](https://github.com/user-attachments/assets/1a9ff290-1f0a-47c5-b844-6b9e28c2abb7)

### Failing version

![Image](https://github.com/user-attachments/assets/907177a0-abb4-4d8e-ac4c-4e3f10aed8f9)
![Image](https://github.com/user-attachments/assets/39a611ab-5fca-4b1f-901e-987f40768ab2)

**Comment by hemanthmanga** [comment]
Hi @williamho123, Thank you for bringing this issue to our attention. We will look into this issue and will update you after investigating.

**Comment by Prabhatkumar59** [comment]
Hi @williamho123 - Could you please try once to rerun your workflows and let us know.

**Comment by williamho123** [comment]
Hi @Prabhatkumar59 -- I re-ran our workflow, and I still see that my current user is `runner` but the `packer` user is the owner of the directory.

When `actions/cache@v4` tries to restore the cache, I still get the same permissions issues. However, the entire workflow does  not fail anymore. 

1. How come this is the case? What changed in the backend?
2. Is the user owning the directory expected to be `packer`?

**Comment by Prabhatkumar59** [comment]
Hi @williamho123 - Thanks for the input!, we will look into this further and will update you accordingly, thank you!

**Comment by Alexey-Ayupov** [comment]
Hay @williamho123, we fixed the directory owner. The next version of the image will have this fix.

**Comment by williamho123** [comment]
> Hay [@williamho123](https://github.com/williamho123), we fixed the directory owner. The next version of the image will have this fix.

Hi @Alexey-Ayupov -- thanks for the update. Could you provide some more details about what images this was affecting?

From my original issue description, `20250427.1.0` was problematic but a newer version of `20250504.1.0` was working. Does that mean it was already fixed in `20250504.1.0`?

Or does this have to do with the differing versions of the Runner Image Provisioner? (I am not sure what that is)

**Comment by Prabhatkumar59** [comment]
As per above comment from @Alexey-Ayupov - We have fixed the directory owner. Please try to update your sync process and use latest image version. We are closing this issue for now, thanks.

**Comment by williamho123** [comment]
@Prabhatkumar59 @Alexey-Ayupov This is not fixed. We should re-open the issue.

For a recent run from this morning, I have this snippet as part of my CI workflow.

```bash
current_user=$(whoami)
python_install_owner=$(ls -ld /opt/hostedtoolcache/Python/3.10.17/x64 | cut -d' ' -f3)
  
if [[ "$python_install_owner" != "$current_user" ]]; then
  echo "WARNING: Python install owner is not '$current_user'. It is '$python_install_owner'."
fi
```

I got the warning:

![Image](https://github.com/user-attachments/assets/d693adca-5975-48b3-8896-892b933574e6)

Runner versions
![Image](https://github.com/user-attachments/assets/f868766b-d995-4c2c-90e8-34adec3e9bd6)

How come it is still showing a different user?

> Please try to update your sync process and use latest image version

How do I do that? I am using Github Hosted Runners and do not have control over the image version.
