### ISSUE TITLE
macOS hostname DNS resolution failure

### ISSUE THREAD

**Issue by externl** [actions/runner-images#12562]
### Description

Getting the hostname of the runner then pinging it fails.

Maybe related to https://github.com/actions/runner-images/issues/12560, but we started experiencing these issues at different times. This issue is intermittent. 

```
Run set -x
++ hostname
+ echo 'Hostname: Mac-1752083390647.local'
Hostname: Mac-1752083390647.local
++ hostname -f
+ echo 'Fully Qualified Domain Name: Mac-1752083390647.local'
Fully Qualified Domain Name: Mac-1752083390647.local
+ echo 'Pinging localhost...'
Pinging localhost...
+ ping -c 1 localhost
PING localhost (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.157 ms
--- localhost ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.157/0.157/0.157/0.000 ms
+ echo 'Pinging hostname...'
Pinging hostname...
++ hostname
+ ping -c 1 Mac-1752083390647.local
ping: cannot resolve Mac-1752083390647.local: Unknown host
```

See also my test workflow failure: https://github.com/externl/sandbox/actions/runs/16176523130/job/45662855741

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [x] macOS 15
- [x] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

```
Runner Image
  Image: macos-15-arm64
  Version: 20250630.1914
  Included Software: https://github.com/actions/runner-images/blob/macos-15-arm64/20250630.1914/images/macos/macos-15-arm64-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-15-arm64%2F20250630.1914
```

### Is it regression?

Yes

### Expected behavior

Hostname should be resolvable. 

### Actual behavior

Hostname is not always resolvable.  If it works once on a runner it seems to always work, but if it fails it will always fail.

````
ping: cannot resolve Mac-1752083390647.local: Unknown host
```
where `Mac-1752083390647.local` is hostname

### Repro steps

ping -c 1 $(hostname)

**Comment by ijunaidm1** [comment]
Hi @externl - We will start investigating on this issue and will update you accordingly.

**Comment by susmitamane** [comment]
Hi @externl,

- We investigated the issue you're facing and found that on macOS runners, the hostname is dynamically generated (e.g., Mac-<random>.local). 
- These hostnames are not DNS-resolvable, and even commands like hostname -f or scutil --get LocalHostName return names that can't be resolved.

- As a workaround, you can try the following command instead, which gives the expected result:

```
echo "Hostname: $(hostname)"
ping -c 1 localhost
```

- Please refer to the workflow screenshot below for more details:

<img width="878" height="649" alt="Image" src="https://github.com/user-attachments/assets/3bf96562-8a9f-416d-a104-ef4b2808c02a" />

**Comment by susmitamane** [comment]
- Hi @externl, the issue has been resolved with the latest deployments. It was caused by a 49s error, It was caused by a 49s error that has been addressed.
- I've tested the workflow you shared using the provided reproducing steps, and it is now working correctly with no errors and the expected output.
- Could you please verify from your end and confirm?
<img width="707" height="443" alt="Image" src="https://github.com/user-attachments/assets/02f8fe9d-9f4f-4c79-ab50-60fc7261a14f" />

Thanks!

**Comment by externl** [comment]
Hi @susmitamane, I'll try running my workflow a few times to see it's still happening and get back to you. What's 49s error?

EDIT: Ran my workflow about 10 times, no errors. This issue seems to be fixed.

**Comment by susmitamane** [comment]
Hi @externl,

Thank you for the confirmation. We are closing this issue as resolved. Please feel free to reach out if you encounter any new issues related to macOS.

Thanks again!

**Comment by externl** [comment]
@susmitamane This has started occurring again today. Was working fine all week.

**Comment by nodeselector** [comment]
@externl we're rolling out some changes that shoud help avoid this. It should be rolled out by the end of this week. Please send us the contents of `/etc/hosts` if you do see this again. 🙇

**Comment by externl** [comment]
Still getting this error FYI. Will follow-up with contents of `/etc/hosts`.

**Comment by externl** [comment]
@nodeselector 

Ok, I was able to reproduce:

Run 1 (good):
- https://github.com/externl/sandbox/actions/runs/17413837219/job/49437316731
```
cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
192.168.64.24 sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-CE73250A4CBD.local sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-CE73250A4CBD
```

```
++ hostname
+ echo 'Hostname: sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-CE73250A4CBD.local'
Hostname: sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-CE73250A4CBD.local
++ hostname -f
+ echo 'Fully Qualified Domain Name: sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-CE73250A4CBD.local'
Fully Qualified Domain Name: sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-CE73250A4CBD.local
+ echo 'Pinging localhost...'
+ ping -c 1 localhost
Pinging localhost...
PING localhost (127.0.0.1): 56 data bytes
+ echo 'Pinging hostname...'
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.035 ms

--- localhost ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
++ hostname
round-trip min/avg/max/stddev = 0.035/0.035/0.035/nan ms
Pinging hostname...
+ ping -c 1 sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-CE73250A4CBD.local
PING sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-ce73250a4cbd.local (192.168.64.24): 56 data bytes
+ echo 'Pinging FQDN...'
64 bytes from 192.168.64.24: icmp_seq=0 ttl=64 time=0.039 ms
++ hostname -f

--- sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-ce73250a4cbd.local ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.039/0.039/0.039/0.000 ms
Pinging FQDN...
+ ping -c 1 sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-CE73250A4CBD.local
PING sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-ce73250a4cbd.local (192.168.64.24): 56 data bytes
64 bytes from 192.168.64.24: icmp_seq=0 ttl=64 time=0.037 ms

--- sjc20-bb710_726b6e3a-6405-4372-8f05-c88d6f9c9f49-ce73250a4cbd.local ping statistics ---
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.037/0.037/0.037/nan ms
```

Run2 2 (failure):
- https://github.com/externl/sandbox/actions/runs/17413837219/job/49437429593#step:4:33
```
cat /etc/hosts
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
192.168.64.24 iad20-fj917_6cae4d32-d0ce-456c-8173-514448759e72-FE7BB458E416.local iad20-fj917_6cae4d32-d0ce-456c-8173-514448759e72-FE7BB458E416
```

```
++ hostname
+ echo 'Hostname: Mac-1756841190941.local'
Hostname: Mac-1756841190941.local
++ hostname -f
+ echo 'Fully Qualified Domain Name: Mac-1756841190941.local'
Fully Qualified Domain Name: Mac-1756841190941.local
+ echo 'Pinging localhost...'
+ ping -c 1 localhost
Pinging localhost...
PING localhost (127.0.0.1): 56 data bytes
+ echo 'Pinging hostname...'
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.077 ms

--- localhost ping statistics ---
++ hostname
1 packets transmitted, 1 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 0.077/0.077/0.077/0.000 ms
Pinging hostname...
+ ping -c 1 Mac-1756841190941.local
ping: cannot resolve Mac-1756841190941.local: Unknown host
```

The hostname does not match anything in `/etc/hosts`.

**Comment by vieiro** [comment]
Hi.

This happened a while back with `macos-13` GHA runners too, reported as https://github.com/actions/runner-images/issues/8649 

The problem happens intermittently in `macos-15-intel` GHA runners too.

A reproducer can be found here:  https://github.com/vieiro/gha-macos-resolve-hostname

(Just clone the repo and take a look at the tests, e.g. [these](https://github.com/vieiro/gha-macos-resolve-hostname/actions/runs/19362994247)) .

The problem, I think, is that people are abusing `getaddrinfo` to fetch local addresses, and this is probably not a very good idea:

- `.local` addresses can't be top level domains  (see, [.local](https://en.wikipedia.org/wiki/.local)). 
- `getaddrinfo` is not expected to be used to resolve [local addresses](https://stackoverflow.com/questions/2146191/obtaining-local-ip-address-using-getaddrinfo-c-function).

A workaround is to add the hostname to `/etc/hosts`:

```
      - name: 'Update /etc/hosts on macos'
        run: |
          echo -e "127.0.0.1     $(hostname -f) $(hostname -s)" | sudo tee -a /etc/hosts
          echo -e "" | sudo tee -a /etc/hosts
        if: runner.os == 'macOS'
```
