### ISSUE TITLE
macOS-15 runner fails to start iOS simulator

### ISSUE THREAD

**Issue by smoogipoo** [actions/runner-images#12862]
### Description

Hi, I'm coming from a recently closed issue report: https://github.com/actions/runner-images/issues/12758

The suggested solution listed is to `xcode-select` and (potentially?) download the iOS platform. For us, we're using Xcode 16.4 and downloading the latest platform (no args).

50% of the time, this works and resolves the original issye. 50% of the time, it results in another issue:
```
Unable to connect to simulator.
```

See for example this run: https://github.com/ppy/osu/actions/runs/17115759241/job/48546246056?pr=33649

Please help!

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [x] macOS 15 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

20250818.2206

### Is it regression?

Yes, 20250722.2025, https://github.com/ppy/osu/actions/runs/17068261106/job/48390499090

### Expected behavior

The "Use Xcode 16.4" step in the linked workflow to work.

### Actual behavior

```
Unable to connect to simulator.
```

### Repro steps

```
sudo xcode-select -switch /Applications/Xcode_16.4.app
xcodebuild -downloadPlatform iOS
```

**Comment by smoogipoo** [comment]
Have also tracked down a [pass](https://github.com/ppy/osu/actions/runs/17091512765/job/48466111503) and [fail](https://github.com/ppy/osu/actions/runs/17067561891/job/48388261018) in a more recent runner image `20250811.2170`, so seems intermittent on the same image.

**Comment by Jon889** [comment]
I've also found this, even before the recent changes, that sometimes an agent will give the error `Unable to connect to simulator.` when running `xcodebuild -downloadPlatform`. @erik-bershel  It seems there is an inconsistency in the runners, even within the same image version. Perhaps you could add the workaround below and information about the error to the comment in the locked thread.

@smoogipoo 
As a workaround I run a simctl command before and that seems to fix it, and only adds a couple of seconds to the run time.
This is script I use to set up each job, the second line is the workaround, and the versions for Xcode and simulator could be anything.

```bash
sudo xcode-select -s "/Applications/Xcode_16.4.app"
xcrun simctl list > /dev/null # Required to prevent the next command from sometimes not working
xcodebuild -downloadPlatform iOS -buildVersion 17.4
```

(I know there is a community Task that does installation but as a company policy we're not allowed to use 3rd party tasks)

**Comment by erik-bershel** [comment]
Hey there! 👋 

This is actually a completely different issue for a number of reasons. The original issue was missing simulators for some Xcodes. For Xcode 16.4, this shouldn't be a problem at all - we install all the major simulators for it beforehand. So yes, you've brought a new interesting case that will be useful to investigate and fix. 🤔 
The repro steps are simple, there's enough information, so it shouldn't be hard to reproduce the issue - we'll come back after further investigation. It seems the reason is on our side - we need to conduct a couple of checks.

**Comment by erik-bershel** [comment]
@smoogipoo 

An easier workaround for those using Xcode 16.4 would be to not use the `xcodebuilds -downloadPlatform iOS` command. This is not required for this version of Xcode - all simulators for it are already installed.

Example builds: [1](https://github.com/erik-bershel/osu/actions/runs/17123061533/job/48568272710), [2](https://github.com/erik-bershel/osu/actions/runs/17123219390/job/48568790060).

**Comment by alainib** [comment]
same error for me after the failure and fix from https://github.com/actions/runner-images/issues/12758#issuecomment-3206748945

i runned the CI on github 3times to pass this steps.  i guess i have to update to XCODE 16.4 soon

      - name: Select Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Download iOS Platform
        run: xcodebuild -downloadPlatform iOS

**Comment by Jon889** [comment]
> Hey there! 👋
> 
> This is actually a completely different issue for a number of reasons. The original issue was missing simulators for some Xcodes. For Xcode 16.4, this shouldn't be a problem at all - we install all the major simulators for it beforehand. So yes, you've brought a new interesting case that will be useful to investigate and fix. 🤔 The repro steps are simple, there's enough information, so it shouldn't be hard to reproduce the issue - we'll come back after further investigation. It seems the reason is on our side - we need to conduct a couple of checks.

I noticed some people in that locked thread had the error `Unable to connect to simulator.` because now they are having to use the downloadPlatform command. So yes it’s not because of that change, but more people will be affected by this issue because of that one.

**Comment by erik-bershel** [comment]
After investigating, I still haven't found a clear reason - only set of images generated about the same date are affected. Looks like another consequence of the Xcode 26 beta runtime compatibility issues. Will be fixed in the upcoming release next week.

**Comment by erik-bershel** [comment]
Reproduced similar behavior locally with installed runtimes for Xcode 26. Behavior repeats after switching Xcode for each instance. After removing the updated simcorrruntime, behavior disappears. The next rollout should fix the issue.

**Comment by sagban** [comment]
As suggested in issue #12758, I am manually selecting XCode 16.2 and installing the iOS SDK. As OP mentioned, 50% of the times it gets failed and returns with

```
Finding content...Unable to connect to simulator.

##[error]Bash exited with code '70'.
```
Command used:
```
sudo xcode-select --switch /Applications/Xcode_16.2.app/Contents/Developer
xcodebuild -downloadPlatform iOS
```

**Comment by jcesarmobile** [comment]
~~What worked for me was to add `-exportPath ~/Downloads`, but might have been just one of those 50% of times that succeeds.~~

Yeah, it was one of those 50%, still failing from time to time...

**Comment by erik-bershel** [comment]
Hey there!

I've done some more in-depth testing and found out the following. The problem is caused by several factors. Ultimately, this particular error is caused by the core simulator not being able to rebuild all the caches in the allotted time, and the command crashes. The problem was rare while `Xcode 16.0` was the default version, since it currently has the slowest simulators in the image. The problem started to appear more frequently after adding the Xcode 26 beta runtimes, since this update also affected the core simulator runtime, which is the source of the problem for us. Most likely, after the release of the new stable version, which we will have to add to the image, the problem will get worse again, although not as much as it was with the `beta` version.

Unfortunately, we can only fully solve the problem for simulators that are already installed and that belong to the default Xcode, which is `Xcode 16.4` at the moment.

The easiest way to get around the problem in runtime is to kick the core so that it rebuilds the list of available simulators and caches before direct access. This can be done by running a simple command recommended by @Jon889:

```bash
   xcrun simctl list > /dev/null
```

Here I will give examples of how this behavior manifests itself [before](https://github.com/bbq-beets/bershel-test/actions/runs/17344560802) and [after](https://github.com/bbq-beets/bershel-test/actions/runs/17344798508) applying the runtime fix. I should immediately clarify that in production builds the problem will probably manifest itself a little more often, including sometimes occurring for `Xcode 16.1` and `Xcode 16.2`. In my tests, the core simruntime has a little more time to rebuild caches due to the fact that I use a wrapper for the timeout.

Stay tuned!

**Comment by erik-bershel** [comment]
The image deployment without beta runtimes is complete. This should ease the pressure for those using `Xcode 16.1` and newer. The workaround for `Xcode 16.0` users is above. I recommend using it for all non-default versions of Xcode.

I have to close this ticket as there is nothing more we can do here. 😞
