### ISSUE TITLE
Update .NET 10 SDK

### ISSUE THREAD

**Issue by sdcb** [actions/runner-images#13294]
### Tool name

.NET 10 SDK

### Tool license

MIT

### Add or update?

- [ ] Add
- [x] Update

### Desired version

10

### Approximate size

100MB

### URL for tool's homepage

https://dotnet.microsoft.com/en-us/download/dotnet/10.0

### Provide a basic test case to validate the tool's functionality.

```bash

```

### Platforms where you need the tool

- [x] Azure DevOps
- [x] GitHub Actions

### Runner images where you need the tool

- [x] Ubuntu 22.04
- [x] Ubuntu 24.04
- [x] Ubuntu Slim
- [x] macOS 13
- [x] macOS 13 Arm64
- [x] macOS 14
- [x] macOS 14 Arm64
- [x] macOS 15
- [x] macOS 15 Arm64
- [x] macOS 26 Arm64
- [x] Windows Server 2019
- [x] Windows Server 2022
- [x] Windows Server 2025

### Can this tool be installed during the build?

```bash

```

**Comment by taylorhutchison** [comment]
Need this on Azure DevOps too.

**Comment by sdcb** [comment]
well, although I don't need, but I hit the Azure DevOps checkbox now, hope it helps

**Comment by erik-bershel** [comment]
Will be added as soon as possible. 👍

**Comment by forgetaboutit** [comment]
Will this be available next week in the regular image release cadence?

**Comment by w3sourcecode** [comment]
Thanks for opening this issue — I’m also waiting for the update to .NET 10; does the team have an estimated timeline?

**Comment by erik-bershel** [comment]
Ubuntu images are in the process of being rolled out, Windows images will receive .NET 10 with the next update, but Mac OS images are still waiting - there's a long backlog of updates, so I can't give a specific timeline.

**Comment by sdcb** [comment]
Good news, I can confirm my open source chats project is able to use .NET 10 SDK from ubuntu now: https://github.com/sdcb/chats/actions/runs/19360765357/job/55391921890

And it showed this updated image: https://github.com/actions/runner-images/blob/ubuntu24/20251112.124/images/ubuntu/Ubuntu2404-Readme.md already showed .NET 10 SDK

Although sometimes it still use the old https://github.com/actions/runner-images/blob/ubuntu24/20251102.99/images/ubuntu/Ubuntu2404-Readme.md version.

it should no need to way long time to completely roll out.

**Comment by taylorhutchison** [comment]
For anyone else like me in the Azure DevOps boat, .NET 10 still not rolled out to us yet. We are using the ubuntu-latest agent pool. Expecting it to happen soon based on the above conversation.

**Comment by BrandanN21** [comment]
Following to await the NET 10 updates to MacOS agents. We are in need of NET 10 to get around some .NET MAUI Android updates that are required to account for Google Play Store Policy Updates that should be resolved with MAUI 10.

**Comment by forgetaboutit** [comment]
> For anyone else like me in the Azure DevOps boat, .NET 10 still not rolled out to us yet. We are using the ubuntu-latest agent pool. Expecting it to happen soon based on the above conversation.

Commit https://github.com/actions/runner-images/commit/f4280c339bc51fc2614de261eab9533bb23da4ee lists .NET SDK 10.0.100 support for `ubuntu-latest`. Unfortunately, I have not been successful in building for SDK 10.0 so far. Fingers crossed the latest image will roll out soon.

*Edit*: Nevermind, it's just me. Setting the SDK version for the `UseDotNet@2` task in my `global.json` file to `10.0.100` resolves the issue. Builds on Azure Pipelines are working perfectly now.

**Comment by matthew25187** [comment]
Unfortunately, the official "included software" lists are still not showing the .Net 10 SDK for any of the [Windows hosted agent images](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=windows-images%2Cyaml).  A week on from the release of .Net 10 and I still can't update my NuGet packages for the latest .Net.

**Comment by erik-bershel** [comment]
>Unfortunately, the official "included software" lists are still not showing the .Net 10 SDK for any of the [Windows hosted agent images](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=windows-images%2Cyaml). A week on from the release of .Net 10 and I still can't update my NuGet packages for the latest .Net.

Rollout of Windows Server images with .NET 10 SDK was just started. But! At the same time .NET 10 SDK should be available for usage via [UseDotNet@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines) on Azure DevOps and via [setup-dotnet@v5](https://github.com/actions/setup-dotnet) on GitHub Actions. Feel free to use it to configure environment as needed.

**Comment by matthew25187** [comment]
> > Unfortunately, the official "included software" lists are still not showing the .Net 10 SDK for any of the [Windows hosted agent images](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=windows-images%2Cyaml). A week on from the release of .Net 10 and I still can't update my NuGet packages for the latest .Net.
> 
> ... At the same time .NET 10 SDK should be available for usage via [UseDotNet@2](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/use-dotnet-v2?view=azure-pipelines) on Azure DevOps and via [setup-dotnet@v5](https://github.com/actions/setup-dotnet) on GitHub Actions. Feel free to use it to configure environment as needed.

This is not a reasonable option in my case.  Though I did start trying to use `UseDotNet` to force installation of the .Net 10 SDK, I quickly gave up on that idea when it became clear that extensive changes would be required to my pipeline to resolve all related issues.  As my pipeline is rather complicated with several stages and a large number of jobs, too many changes would be needed for what should be a temporary situation and would later have to be removed again to avoid unnecessary clutter.  Therefore, I am for now completely blocked from producing any new package versions as I have already added .Net 10 targets to my projects in anticipation of rolling out support for this in my next major release.

**Comment by FreakyAli** [comment]
I really need this, its annoying to manually release NuGet's. 
@erik-bershel You think its coming soon?

**Comment by erik-bershel** [comment]
Hey @FreakyAli! 👋 

Well, we were planning to finish it during the release week, but here we are. 😄 I have high hopes that we'll be able to finish rolling out the images with .NET 10 by Monday, but I can't make any promises, as we've already had two rollbacks in a row.

**Comment by FreakyAli** [comment]
@erik-bershel  Hey man no worries, just wanted to see if its soon thanks for the quick update.

**Comment by klogan-omnitech** [comment]
@erik-bershel will this include Visual Studio 2026 and/or MSBuild 180.0.2?

**Comment by alexbal49** [comment]
@klogan-omnitech The Windows Image Update on pull requests have 17.14.36717.8 who is latest version of  Visual Studio 2022

**Comment by ghost** [comment]
@klogan-omnitech It doesn't

<img width="835" height="390" alt="Image" src="https://github.com/user-attachments/assets/3f638aa5-8327-4090-861d-bc747656252d" />

**Comment by donovanp3030** [comment]
Hi @erik-bershel,

Do you have an update on the rollout? I see that you were hoping to get it out by Monday. Thanks!

**Comment by wjdavis5** [comment]
We started seeing failures in our publish tasks once this new image got picked up.
Its failing intermittently today based upon which agent version we get during the run.

The publish task:


```
- task: DotNetCoreCLI@2
      displayName: 'Publish Function App'
      inputs:
        command: publish
        publishWebProjects: false
        continueOnError: false
        projects: |
          **/*Functions.csproj
        arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/Functions'
```


Is failing with: 

```
##[debug]Agent environment resources - Disk: D:\ Available 73484.08 MB out of 76798.00 MB, Memory: Used 3649.00 MB out of 8191.00 MB, CPU: Usage 100.00%
##[debug]Exit code 0 received from tool 'C:\Program Files\dotnet\dotnet.exe'

##[debug]STDIO streams have closed for tool 'C:\Program Files\dotnet\dotnet.exe'
##[debug]modifyOutputPath=true
##[debug]Zip Source: D:\a\1\a\Functions\Functions
##[debug]Zip arguments: Source: D:\a\1\a\Functions\Functions , target: D:\a\1\a\Functions\Functions.zip
##[debug]Successfully created archive D:\a\1\a\Functions\Functions.zip
##[debug]rm -rf D:\a\1\a\Functions\Functions
##[debug]removing directory D:\a\1\a\Functions\Functions
D:\a\1\a\Functions\Functions\Microsoft.OData.Edm.dll - The process cannot access the file because it is being used by another process.
D:\a\1\a\Functions\Functions\System.Diagnostics.DiagnosticSource.dll - The process cannot access the file because it is being used by another process.
D:\a\1\a\Functions\Functions\System.ServiceModel.NetFramingBase.dll - The process cannot access the file because it is being used by another process.
D:\a\1\a\Functions\Functions\System.ServiceModel.NetTcp.dll - The process cannot access the file because it is being used by another process.
D:\a\1\a\Functions\Functions\System.ServiceModel.Primitives.dll - The process cannot access the file because it is being used by another process.
D:\a\1\a\Functions\Functions\System.ServiceModel.Security.dll - The process cannot access the file because it is being used by another process.
##[error]Error: Failed rmRF: EPERM: operation not permitted, unlink 'D:\a\1\a\Functions\Functions'
##[debug]Processed: ##vso[task.issue type=error;source=TaskInternal;correlationId=9308ae01-d479-482d-9c36-fb1a3f6ff109;]Error: Failed rmRF: EPERM: operation not permitted, unlink 'D:\a\1\a\Functions\Functions'

```

Initialize Job Log Snip:

```

Starting: Initialize job
Agent name: 'Azure Pipelines 7'
Agent machine name: 'runnervmmq45y'
Current agent version: '4.264.2'
Runner Image Provisioner
Hosted Compute Agent
Version: 20251124.448
Commit: fda5086b43ec66ade217e5fcd18146c879571177
Build Date: 2025-11-24T21:16:26Z
Operating System
Microsoft Windows Server 2025
10.0.26100
Datacenter
Runner Image
Image: windows-2025
Version: 20251125.122.1
Included Software: https://github.com/actions/runner-images/blob/win25/20251125.122/images/windows/Windows2025-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win25%2F20251125.122
Current image version: '20251125.122.1'
Agent running as: 'VssAdministrator'
```

However when we pull an agent with this config it works fine (no differences in the pipeline, just luck of the draw on which agent we get

```
Agent name: 'Azure Pipelines 8'
Agent machine name: 'runnervmtnls7'
Current agent version: '4.261.0'
Runner Image Provisioner
Hosted Compute Agent
Version: 20251016.436
Commit: 8ab8ac8bfd662a3739dab9fe09456aba92132568
Build Date: 2025-10-15T20:44:12Z
Operating System
Microsoft Windows Server 2025
10.0.26100
Datacenter
Runner Image
Image: windows-2025
Version: 20251102.77.1

```

**Comment by erik-bershel** [comment]
Hey there! 👋 

@klogan-omnitech, please track VS2026 news here: https://github.com/actions/runner-images/issues/13291

@donovanp3030, Ubuntu images were updated, macOS images were updated, Windows images are in progress (almost complete at the moment).

@wjdavis5, please open a bug report with all the required information if you'd like us to investigate any unexpected behavior or regression. This work item will be closed once Windows images rollout is complete.

**Comment by erik-bershel** [comment]
Image rollout is complete.

**Comment by yuyoyuppe** [comment]
Hey @erik-bershel, thank you for taking care of this!

Do you know if there're any plans of upgrading [`partner-runner-images`](https://github.com/actions/runner-images)? We're using `windows-11arm-8core-arm64` aka `Microsoft Windows 11 Desktop by Arm Limited`.

**Comment by erik-bershel** [comment]
Hey @yuyoyuppe!

> Do you know if there're any plans of upgrading [partner-runner-images](https://github.com/actions/runner-images)? We're using windows-11arm-8core-arm64 aka Microsoft Windows 11 Desktop by Arm Limited.

I'm not sure. It might make sense to open an issue in their [repository](https://github.com/actions/partner-runner-images/issues). This is a separate project. 🤷‍♂️
