### ISSUE TITLE
GitHub Actions has encountered an internal error when running your job.

### ISSUE THREAD

**Issue by mwisner** [actions/runner-images#6131]
### Description

Hi,

Within the past few days one specific repo of ours has started receiving:

```
GitHub Actions has encountered an internal error when running your job.
```

Before this, our workflows ran flawlessly for at least the past year, and we have many other repos that have had no issues

I've created a very basic workflow:

```yaml
name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        run: echo "test test test"
```

Within the repo in question, this workflow, along with all the other workflows fail. Things I've tried:

- Changing out the `runs-on` to `macos-latest`, `ubuntu-22.04` etc... (The same result)
- Copy this exact same workflow into a new repo (success)

Is there anything repo-specific that would cause this error? 

Note: We are using GH enterprise cloud.

I'm at a bit of a loss here.... Any help or recommendations would be much appreciated. 

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

`ubuntu-latest`

### Is it regression?

yes

### Expected behavior

runs

### Actual behavior

Error: GitHub Actions has encountered an internal error when running your job.

### Repro steps

n/a.

**Comment by mikhailkoliada** [comment]
@mwisner Hi! could you provide a link to the real workflow runs?

**Comment by mwisner** [comment]
HI @mikhailkoliada,

Thank you for reviewing this issue... Sadly this is a private repo, so I am not sure how to provide the link.

**Comment by mwisner** [comment]
It seems like our issues were resolved. Not sure what happened to be honest but ran them again a few hours later and they started working again. Appreciate you reviewing this issue either way!

**Comment by douglas-wang** [comment]
This seems like still happening here. https://github.com/mdvip/middleware/actions/runs/5348462958
Can anyone take a look?

**Comment by casey-robertson-paypal** [comment]
we are having the same issue

**Comment by daveclinecommercehub** [comment]
Likewise:
```github#L1 GitHub Actions has encountered an internal error when running your job.```

What deployed yesterday, fails today.

**Comment by sfdc-afraley** [comment]
Totally unrelated to this particular runner image, but seems Google is brining us all here.  We're having the same issues since around 11:30am EST today June 22, 2023.  In our case it's only jobs with concurrency constraints that are failing.  I've had a ticket opened for a few hours, but no response yet.  Also nothing on https://www.githubstatus.com/ yet.

**Comment by sfdc-afraley** [comment]
Github says the issues are fixed.

**Comment by julienbonastre** [comment]
Yes this is an ever occurring issue at GitHub and they typically just ignore your support request OR make you run in circles around checking your workflow, settings and debug logging for a pipeline thats worked several times before and has had no changes and then magically Poof! The issue resolves itself through no action on your part


Microsoft GitHub are a scam and have the integrity of a gnat. 

Just get used to it.. nice platform and great service but accountability and reliability are not part of the GH core values 🤷‍♂️

**Comment by PartMan7** [comment]
Seems to be down again (erroring out for me on ubuntu and windows; macos is fine)

**Comment by slayoo** [comment]
Happens repeatedly today on one of our repos (e.g., https://github.com/open-atmos/PySDM/actions/runs/11668733036/job/32497608118):
![image](https://github.com/user-attachments/assets/8a463055-3172-436c-aeb4-530dedf8a73e)

**Comment by slayoo** [comment]
... which seem to be due to the planned GitHub "brownout" of an image in question (macos-12): https://github.com/actions/runner-images/issues/10721

**Comment by Nisarg-Satani-X-arterian** [comment]
<img width="1470" alt="Image" src="https://github.com/user-attachments/assets/89785ef4-31c2-4f90-9ee3-a96c40584d84" />

i am getting this same error but i have self-hosted runners
