### ISSUE TITLE
Install-AndriodSDK.ps1 causes Windows2019/2022 build failure

### ISSUE THREAD

**Issue by PapaDers** [actions/runner-images#6960]
### Description
Update: I ran Windows 2019 this morning and found this same issue.

Starting January 21, 2023 around 1 pm EST, I have had three Windows2022 builds fail on Install-AndriodSDK with the error that -AndroidPackages $platformList is null. I had three builds run in the morning without issue.

I have been running builds back to back while working on modifying the image-generation.yml for my requirements. I have kept all the build files the same, and I didn't update the repo between any of the above builds.

As a test, I fetched the latest upstream this morning and hit the same error. Please let me know what information I should provide, and I am happy to assist! Thanks all for the work that you put into this!

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [x] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

I think I need some help understanding why I am not seeing a "Version" field under my "Initialize Job". If someone can provide me with some direction here I am happy to provide the required information:

```powershell
Starting: Initialize job
Agent name: 'SelfHosted000026'
Agent machine name: 'SelfHosted000026'
Current agent version: '2.214.1'
Current image version: 'dev'
Agent running as: 'AzDevOps'
Prepare build directory.
```

### Is it regression?

I am seeing this as above.

### Expected behavior

Attached are logs from where the build was successful:

[expected.txt](https://github.com/actions/runner-images/files/10474494/expected.txt)

### Actual behavior

Attached are what I am currently seeing:
[failure.txt](https://github.com/actions/runner-images/files/10474497/failure.txt)

### Repro steps

Compile this packer build for Windows2022. For me the failure happens at the 2h 9-10m mark.

**Comment by Alexey-Ayupov** [comment]
Hello @PapaDers, we are working on it, thank you.

**Comment by mikhailkoliada** [comment]
fixed.

**Comment by PapaDers** [comment]
This did fix it for me! Thank you all 💯

**Comment by SahilAshar** [comment]
Howdy - has the new MacOS release of this fix rolled out yet? I'm still seeing this failure in my Android builds on MacOS-12 images unfortunately.
