### ISSUE TITLE
Invoke-RestMethod during toolset installation

### ISSUE THREAD

**Issue by Technomann** [actions/runner-images#6990]
### Description

vhd: Install and upgrade Pip
    vhd: Looking in links: c:\Users\packer\AppData\Local\Temp\tmprb_4j0vo
    vhd: Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.11.1\x86\lib\site-packages (65.5.0)
    vhd: Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.1\x86\lib\site-packages (22.3.1)
    vhd: Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.1\x86\lib\site-packages (22.3.1)
    vhd: Create complete file
==> vhd: Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.
==> vhd: At C:\Windows\Temp\script-63d278e3-53bb-c607-24f7-7c278fc92e61.ps1:39 char:15
==> vhd: +     $assets = Invoke-RestMethod $tool.url
==> vhd: +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
==> vhd:    eption
==> vhd:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
==> vhd:
==> vhd: Script exited with non-zero exit status: 1. Allowed exit codes are: [0]
==> vhd: Step "StepProvision" failed
==> vhd: [c] Clean up and exit, [a] abort without cleanup, or [r] retry step (build may fail even if retry succeeds)?

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Build is private.

### Is it regression?

The last working commit: 9b06b852013a0b207a0f73fc2b9aea75c29287f5

### Expected behavior

The image should be created in Azure.

### Actual behavior

A rest method is aborted due to failure of creating SSL/TLS secure channel.

### Repro steps

1. Checkout the latest Windows2022 NOT pre-release version: 8105753c2c3ac7f1bdec48caaebd35d8d264a6ab
2. Cherry-pick the merge commit from [this](https://github.com/actions/runner-images/pull/6963) PR (it is related to the [issue](https://github.com/actions/runner-images/issues/6989) reported previously: merge commit hash: 44a6abe0b7a4c11cfe2d153a394b76f33cf97fba
3. Follow the instructions in the repository's description and run the `GenerateResourcesAndImage` command

@Alexey-Ayupov suggested the 2nd step previously .

**Comment by Alexey-Ayupov** [comment]
Hello @Technomann, it looks like your environment has not been configured with TLS 1.2
Could you please invoke the next snippet and try again?
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

**Comment by Technomann** [comment]
Hi @Alexey-Ayupov!

The scripts in the repo also contains the line you mentioned above, so this should be set before making the REST call.

For example `Install-PowerShellModules.ps1` has this on the 2nd line.

So this is not a proper solution.

Since the last failure, I checked out the -Latest labeled commit, and still got this same error.

**Comment by Technomann** [comment]
As far as I noticed, for example this is missing from `Install-Toolset.ps1`:
`[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor "Tls12"`

**Comment by Alexey-Ayupov** [comment]
We do not observe any problem in our [image generation](https://github.visualstudio.com/runner-images/_build/results?buildId=130712&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f245de8a-85db-5d11-6f6b-a3b45c2b2a6a) however, we are using the same scripts. 
![image](https://user-images.githubusercontent.com/116575425/215130905-c9bf0078-de5f-4c6f-8d3f-f9bc51124256.png)

**Comment by Technomann** [comment]
Are you using it with service principal or user account authentication?

**Comment by Alexey-Ayupov** [comment]
Yes we are using service principal, you could find more information [here](https://github.com/actions/runner-images/blob/main/images/win/windows2022.json)

**Comment by mikhailkoliada** [comment]
Hello! Fixed in main, please sync your fork.

**Comment by McAdamz** [comment]
This error is still occurring for me when running off main:


    vhd: Install and upgrade Pip
    vhd: Looking in links: c:\Users\packer\AppData\Local\Temp\tmpiohpa4pu
    vhd: Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.11.1\x64\lib\site-packages (65.5.0)
    vhd: Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.1\x64\lib\site-packages (22.3.1)
    vhd: Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.1\x64\lib\site-packages (22.3.1)
    vhd: Collecting pip
    vhd:   Using cached pip-23.0-py3-none-any.whl (2.1 MB)
    vhd: Installing collected packages: pip
    vhd:   Attempting uninstall: pip
    vhd:     Found existing installation: pip 22.3.1
    vhd:     Uninstalling pip-22.3.1:
    vhd:       Successfully uninstalled pip-22.3.1
    vhd: Successfully installed pip-23.0
    vhd: Create complete file
    vhd: Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.
    vhd: At C:\Windows\Temp\script-63d82f35-0989-dc2c-61ae-3d907c8fee2b.ps1:41 char:15
    vhd: +     $assets = Invoke-RestMethod $tool.url
    vhd: +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    vhd:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
    vhd:    eption
    vhd:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
