### ISSUE TITLE
[Windows] Invoke-WebRequest: The Local Security Authority cannot be contacted

### ISSUE THREAD

**Issue by shivammathur** [actions/runner-images#7007]
### Description

`Invoke-WebRequest` is throwing the following exception when fetching a file from GitHub releases.

This exception is thrown
```pwsh
TargetSite     : Void MoveNext()
Message        : Authentication failed, see inner exception.
Data           : {}
InnerException : System.ComponentModel.Win32Exception (0x80090304): The Local Security Authority cannot be contacted
HelpLink       : 
Source         : System.Net.Security
HResult        : -[21](https://github.com/shivammathur/test-setup-php/actions/runs/4041932267/jobs/6949032847#step:2:22)46[23](https://github.com/shivammathur/test-setup-php/actions/runs/4041932267/jobs/6949032847#step:2:24)3087
StackTrace     :    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean 
                 receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
                    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions 
                 sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken 
                 cancellationToken)
```

This behaviour is flaky, it succeeds sometimes and fails sometimes.
Test workflow: https://github.com/shivammathur/test-setup-php/actions/runs/4041932267/workflow

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/shivammathur/test-setup-php/actions/runs/4041932267/workflow

### Is it regression?

Yes

### Expected behavior

Invoke-WebRequest should be able to fetch a file from GitHub Releases

### Actual behavior

This exception is thrown
```pwsh
TargetSite     : Void MoveNext()
Message        : Authentication failed, see inner exception.
Data           : {}
InnerException : System.ComponentModel.Win32Exception (0x80090304): The Local Security Authority cannot be contacted
HelpLink       : 
Source         : System.Net.Security
HResult        : -[21](https://github.com/shivammathur/test-setup-php/actions/runs/4041932267/jobs/6949032847#step:2:22)46[23](https://github.com/shivammathur/test-setup-php/actions/runs/4041932267/jobs/6949032847#step:2:24)3087
StackTrace     :    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean 
                 receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
                    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions 
                 sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken 
                 cancellationToken)
```

### Repro steps

Invoke-WebRequest -UseBasicParsing -Uri https://github.com/shivammathur/php-builder-windows/releases/latest/download/Get-PhpNightly.ps1 -OutFile C:\tools\php\Get-PhpNightly.ps1

**Comment by bogdan-damian-bgd** [comment]
Hey @shivammathur, we tried to reproduce the issue a dozen times and all the requests passed Ok. Seems like flaky network connection and there is not much we can do about it from our side.

**Comment by shivammathur** [comment]
@bogdan-damian-bgd 

Still happens, it is flaky but fails around 40% of the time and is not a one-off network connection issues.
https://github.com/shivammathur/test-setup-php/actions/runs/4043071011

**Comment by mikhailkoliada** [comment]
@shivammathur we will track our telemetry and if needed ask azure to assist

**Comment by derrod** [comment]
We over at @obsproject have seen similar issues, see our recent workflows where roughly 2/3 failed: https://github.com/obsproject/obs-studio/actions/workflows/main.yml

For us they also happen during Windows builds. In our case it's a Powershell script attempting to use `Invoke-WebRequest` and they all fail with the same error as in the initial post (although the actual exception is not surfaced here):
> Authentication failed, see inner exception.

**Comment by mikhailkoliada** [comment]
@shivammathur @derrod as a matter of test, could you please add 

```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13

```

To your powershell snippets/scripts before the actual command invocation?

**Comment by shivammathur** [comment]
@mikhailkoliada 

That fails with the same error.
https://github.com/shivammathur/test-setup-php/actions/runs/4053367973/workflow

**Comment by derrod** [comment]
I've also tested this in my fork and unfortunately it does not appear to work here etiher: https://github.com/derrod/obs-studio/actions/runs/4053763844/jobs/6974779931

**Comment by shivammathur** [comment]
@mikhailkoliada 

Looks like it was fixed in 20230129.1
https://github.com/shivammathur/test-setup-php/actions/runs/4043071011

**Comment by mikhailkoliada** [comment]
@shivammathur hmmm, I am wondering if it was due-to powershell upgrade. Ok, as it is irreproducible now lets close the ticket, but if you see something similar again, feel free to report back with a new ticket :)

**Comment by derrod** [comment]
Sadly we're still seeing failures, these happened less than an hour ago:
- https://github.com/obsproject/obs-studio/actions/runs/4091196699
- https://github.com/obsproject/obs-studio/actions/runs/4091131815

For us the failures started happening around `20230123.1` but that may just be a coincidence. All I can say for sure is that it started happening on January 26th.

**Comment by shivammathur** [comment]
@mikhailkoliada 
I spoke too soon, seems like the issue still exists. We are facing the same issue while downloading the curl CA file. https://github.com/shivammathur/setup-php/issues/699

https://github.com/shivammathur/test-setup-php/actions/runs/4112354765/jobs/7097164119#step:2:1

**Comment by Giorgi** [comment]
I'm still experiencing the issue. I use MSBuild [DownloadFile task](https://learn.microsoft.com/en-us/visualstudio/msbuild/downloadfile-task?view=vs-2022) which fails with the same error.

Four failures in a row.

```
Downloading from "https://github.com/duckdb/duckdb/releases/download/v0.7.0/libduckdb-windows-amd64.zip" to "D:\a\DuckDB.NET\DuckDB.NET\DuckDB.NET\obj\runtimes\win-x64\native.zip" (8,449,189 bytes).
  Downloading from "https://github.com/duckdb/duckdb/releases/download/v0.7.0/libduckdb-windows-i386.zip" to "D:\a\DuckDB.NET\DuckDB.NET\DuckDB.NET\obj\runtimes\win-x86\native.zip" (8079572 bytes).
D:\a\DuckDB.NET\DuckDB.NET\DuckDB.NET\DownloadNativeLibs.targets(4,9): error MSB3923: Failed to download file "https://github.com/duckdb/duckdb/releases/download/v0.7.0/libduckdb-linux-amd64.zip".  Authentication failed, see inner exception.
D:\a\DuckDB.NET\DuckDB.NET\DuckDB.NET\DownloadNativeLibs.targets(4,9): error MSB3923: Failed to download file "https://github.com/duckdb/duckdb/releases/download/v0.7.0/libduckdb-linux-aarch64.zip".  Authentication failed, see inner exception.
```

![image](https://user-images.githubusercontent.com/580749/218480752-909ad65b-b3c9-447d-9298-34d5931c4c28.png)

![image](https://user-images.githubusercontent.com/580749/218480863-e5f8f589-eac0-421f-82c0-e17f3a9ab863.png)

**Comment by Giorgi** [comment]
I still got this error today: https://github.com/Giorgi/DuckDB.NET/actions/runs/4993460350/jobs/8942616309

![image](https://github.com/actions/runner-images/assets/580749/85947dfe-c7fe-47ac-bf55-a04a46fbbff9)

**Comment by weshaggard** [comment]
This is starting to show up randomly in a lot of our windows builds as well. Has anyone found a reliable fix for it?

**Comment by ilia-shipitsin** [comment]
@weshaggard , whos owns DownloadNativeLibs.targets ? Can it use GITHUB_TOKEN ? https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by ilia-shipitsin** [comment]
I've checked https://github.com/loresoft/msbuildtasks and https://github.com/mikefourie-zz/MSBuildExtensionPack , no task exists.

but it sounds as a nice feature to extend native [DownloadFile task](https://github.com/dotnet/msbuild/blob/main/src/Tasks/DownloadFile.cs)

**Comment by Giorgi** [comment]
There is a feature request already: https://github.com/dotnet/msbuild/issues/8105

**Comment by Giorgi** [comment]
For now, I added `Retries="3"` hope it will helps

**Comment by ilia-shipitsin** [comment]
I would add delay as well (if that's possible)

**Comment by Giorgi** [comment]
It didn't help because this error isn't retriable: [IsRetriable](https://github.com/dotnet/msbuild/blob/fe79798bdb36571368176a6b9f8fdd15a5646500/src/Tasks/DownloadFile.cs#L237)

**Comment by weshaggard** [comment]
In my case I'm using a PS script calling Invoke-WebRequest with a retry of 10, and in some cases it completely fails I'm trying to add some more diagnostics to see if I can get a better understanding of the issue. I don't think a token will help as I don't currently expect this is a rate-limiting issue.

**Comment by ilia-shipitsin** [comment]
Full response will help.

I suspect rate limiting because anonymous request are limited by IP, which is likely behind the NAT

**Comment by Cyberboss** [comment]
Can this issue be reopened please? I've also been experiencing it trying to download a GitHub releases asset from my build pipeline.

https://github.com/tgstation/tgstation-server/actions/runs/4975660599/jobs/8975861389
```
 [22:04:54] err: Tgstation.Server.Host.Core.ServerUpdater (Instance:|Job:|Request:PUT /Swarm/Update|User:|Monitor:|Bridge:|Chat:|IR:|Node:)
     Error updating server!
 System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
  ---> System.ComponentModel.Win32Exception (0x80090304): The Local Security Authority cannot be contacted
    --- End of inner exception stack trace ---
    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
    --- End of inner exception stack trace ---
    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
    at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
    at Tgstation.Server.Host.IO.FileDownloader.DownloadFile(Uri url, CancellationToken cancellationToken) in D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\IO\FileDownloader.cs:line 47
    at Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate(String updatePath, CancellationToken cancellationToken, CancellationToken criticalCancellationToken) in D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Core\ServerUpdater.cs:line 186
    at Tgstation.Server.Host.Core.ServerUpdater.ExecuteUpdate(String updatePath, CancellationToken cancellationToken, CancellationToken criticalCancellationToken) in D:\a\tgstation-server\tgstation-server\src\Tgstation.Server.Host\Core\ServerUpdater.cs:line 191
```

**Comment by Cyberboss** [comment]
Adding `Authentication: Bearer <token>` did not work for my case.

**Comment by ilia-shipitsin** [comment]
you are likely right that `System.ComponentModel.Win32Exception (0x80090304): The Local Security Authority cannot be contacted` looks like something not related to api rate limit.

may I ask you to add the following to collect WinEvent logs (maybe there's something interesting)


```
    - name: get logs system
      if: always()
      run: |
         Get-EventLog -LogName System | Format-List
      shell: powershell
      
    - name: get logs application
      if: always()
      run: |
         Get-EventLog -LogName Application | Format-List
      shell: powershell
```

**Comment by Cyberboss** [comment]
Here's the output from one of the failing jobs with those logs included
[actions_output.txt](https://github.com/actions/runner-images/files/11507700/actions_output.txt)

**Comment by weshaggard** [comment]
For my case I tried explicitly setting SSL1.2 and SSL1.3 but it still didn't end up helping. 
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 -bor [Net.SecurityProtocolType]::Tls13`

@mikhailkoliada Any other suggestions for this issue?

**Comment by Cyberboss** [comment]
Downgrading to `windows-2019` for the affected jobs alleviated my issue

**Comment by Giorgi** [comment]
Can confirm, after 4 failed attempts I downgraded to `windows-2019` and it worked

![image](https://github.com/actions/runner-images/assets/580749/37b7b5fd-e010-4b0f-9b7d-eb6657b80a10)
