### ISSUE TITLE
[Windows 2022] Image VM build task failed during python 3.11 pip instalaltion

### ISSUE THREAD

**Issue by fajterini** [actions/runner-images#7023]
### Description

For two days I have problem to build Image runner VM (windows2022) in our environment, it's failing on python installation ?

    vhd:
    vhd:
    vhd:     Directory: C:\hostedtoolcache\windows\Python\3.11.1\x86
    vhd:
    vhd:
    vhd: Mode                 LastWriteTime         Length Name
    vhd: ----                 -------------         ------ ----
    vhd: -a---l          2/1/2023   4:09 AM              0 python3.exe
    vhd: Install and upgrade Pip
    vhd: Looking in links: c:\Users\packer\AppData\Local\Temp\tmptb93ycpb
    vhd: Requirement already satisfied: setuptools in c:\hostedtoolcache\windows\python\3.11.1\x86\lib\site-packages (65.5.0)
    vhd: Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.1\x86\lib\site-packages (22.3.1)
    vhd: Requirement already satisfied: pip in c:\hostedtoolcache\windows\python\3.11.1\x86\lib\site-packages (22.3.1)
    vhd: Collecting pip
    vhd:   Using cached pip-23.0-py3-none-any.whl (2.1 MB)
    vhd: Installing collected packages: pip
    vhd:   Attempting uninstall: pip
    vhd:     Found existing installation: pip 22.3.1
    vhd:     Uninstalling pip-22.3.1:
    vhd:       Successfully uninstalled pip-22.3.1
    vhd: Successfully installed pip-23.0
==> vhd: Invoke-RestMethod : The request was aborted: Could not create SSL/TLS secure channel.
    vhd: Create complete file
==> vhd: At C:\Windows\Temp\script-63d9c7ec-f70e-cbd2-5a72-3ce6540c572e.ps1:41 char:15
==> vhd: +     $assets = Invoke-RestMethod $tool.url
==> vhd: +               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> vhd:     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
==> vhd:    eption
==> vhd:     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
==> vhd:
==> vhd: Provisioning step had errors: Running the cleanup provisioner, if present...
==> vhd: 

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

N/A

### Is it regression?

pobably not

### Expected behavior

VM build task sucessull

### Actual behavior

failed on error

### Repro steps

Check your azure devops same issue is there https://github.visualstudio.com/runner-images/_build/results?buildId=130799&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f245de8a-85db-5d11-6f6b-a3b45c2b2a6a

**Comment by bogdan-damian-bgd** [comment]
Hi @fajterini, it was fixed recently in main, please sync your fork.

If you have any questions feel free to reach us.

**Comment by fajterini** [comment]
Thanks :)

**Comment by fajterini** [comment]
I was too fast :) We are allways using uptodate clone of main repo. So for me this is not fixed. But I will run build againt to test.

**Comment by mikhailkoliada** [comment]
Should be fixed in main, feel free to reach us again if something similar happens :)

**Comment by fajterini** [comment]
Thanks for fast fix :)
