### ISSUE TITLE
Windows Image build failed on Android SDK test

### ISSUE THREAD

**Issue by fajterini** [actions/runner-images#7271]
### Description

Our build of Windows Images is failing on step 
Provisioning with powershell script: C:\azagent\A1\_work\1\s\images\win/scripts/Installers/Install-AndroidSDK.ps1

    vhd:     Expected regular expression 'platforms;android-33-ext4' to match 'Loading package information...                                                   Loading local repository...                | tools                                                                             ', but it did not match.
    vhd:     at "$installedPackages" | Should -Match "$platformVersion", C:\image\Tests\Android.Tests.ps1:75
    vhd:     at <ScriptBlock>, C:\image\Tests\Android.Tests.ps1:75

Issue started on Friday 10.03 for us.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Android SDK test is not working correctly ?

https://github.visualstudio.com/runner-images/_build/results?buildId=131552&view=logs&j=747417c8-a650-5aed-afed-d9b52dbd7d24&t=f245de8a-85db-5d11-6f6b-a3b45c2b2a6a

### Is it regression?

N/A

### Expected behavior

Image build scessful

### Actual behavior

Adroid SDK test is not woring correctly ?

### Repro steps

Adroid SDK test is not working correctly ?

**Comment by erik-bershel** [comment]
Hi @fajterini @jlbfenergo! We are in process of resolving that issue. Changes would be published soon.

**Comment by mikhailkoliada** [comment]
fixed in main

**Comment by erik-bershel** [comment]
@Shadee159 please update your fork. Issue was fixed here: https://github.com/actions/runner-images/pull/7280. You may check logs of test builds here: https://github.visualstudio.com/08427f54-005b-4b34-b700-dca767ba7c14/_build/results?buildId=131567.

**Comment by Shadee159** [comment]
@erik-bershel yeah I saw it that yesterday everything successfully completes. And yes I'm running with the latest fork which has this issue fixed. Bet error still persists. 

Below is checkout stage with the latest fork.

`
 * [new tag]           ubuntu18/20230217.2    -> ubuntu18/20230217.2
git checkout --progress --force bc22983319daa620b2ad01a74b68f6f462d86241
Note: switching to 'bc22983319daa620b2ad01a74b68f6f462d86241'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:
  git switch -c <new-branch-name>
Or undo this operation with:
 git switch -
Turn off this advice by setting config variable advice.detachedHead to false
**HEAD is now at bc229833 Update condition for Android packages filter (#7280)
Finishing: Checkout actions/runner-images@main to runner-images**

`

**Comment by jlbfenergo** [comment]
I can confirm that the fix on https://github.com/actions/runner-images/commit/bc22983319daa620b2ad01a74b68f6f462d86241 worked for us when building windows 2019 image.

**Comment by erik-bershel** [comment]
@Shadee159 still the same answer. I sure that your issue is connected with source code version. Current deployment is running with images which were build from that code.
