### ISSUE TITLE
macOS 13 runner also needs Xcode UI testing capabilities 

### ISSUE THREAD

**Issue by erikng** [actions/runner-images#7621]
### Description

Someone had reported this for the macOS 12 runner https://github.com/actions/runner-images/issues/5410 

https://github.com/actions/runner-images/pull/5417 solved for it, but unfortunately this logic wasn't updated for the 13 runner https://github.com/actions/runner-images/blob/main/images/macos/provision/configuration/configure-machine.sh#L60

This needs to be updated to be performed on macOS 12 and higher

My CI job is failing due to this

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/macadmins/nudge/actions/runs/5026342911/jobs/9014503504

### Is it regression?

yes

### Expected behavior

xcode ui unit tests should work

### Actual behavior

they don't work

### Repro steps

Run xcode ui tests on a project, see that they fail.

**Comment by erik-bershel** [comment]
Hey @erikng!
We'll take a look.

**Comment by mikhailkoliada** [comment]
Should be fixed

**Comment by erikng** [comment]
Thanks. I'll revert some of my Ui test skips and test it out.

**Comment by drewvolz** [comment]
I think I am still seeing macOS 13 time out around `automationmodetool` with a combination of:
- macOS 13.0 (cannot test on 13.1, odd payment issues are being returned)
- Xcode 14.2.0

[Here is a link to the job](https://github.com/drewvolz/class-dumper/actions/runs/5218561742/jobs/9419463167).

```
  Executed 2 tests, with 0 failures (0 unexpected) in 0.004 (0.006) seconds
  2023-06-09 05:23:37.837 xcodebuild[9911:53033] [MT] IDETestOperationsObserverDebug: 66.451 elapsed -- Testing started completed.
  2023-06-09 05:23:37.837 xcodebuild[9911:53033] [MT] IDETestOperationsObserverDebug: 0.000 sec, +0.000 sec -- start
  2023-06-09 05:23:37.837 xcodebuild[9911:53033] [MT] IDETestOperationsObserverDebug: 66.451 sec, +66.451 sec -- end
  Testing failed:
  	ClassDumperUITests-Runner (11878) encountered an error
  	(The test runner failed to initialize for UI testing. If you believe this error represents a bug,
  	please attach the result bundle at /Users/runner/work/class-dumper/class-dumper/test.xcresult.
  	(Underlying Error: Timed out while enabling automation mode.))
  
  ** TEST FAILED **
```

**Comment by drewvolz** [comment]
Could the underlying issue here be #7531 where macOS 13 runners are having issues running applescript/osascript?

**Comment by idigra** [comment]
> Could the underlying issue here be #7531 where macOS 13 runners are having issues running applescript/osascript?

As far as I can see the root cause is the same as the original bug here and not related to https://github.com/actions/runner-images/issues/7531. I added ```automationmodetool``` powershell command in my pipeline that is failing too, and got following output:

    Automation Mode is disabled.
    This device requires user authentication to enable Automation Mode.

While in ```macos-12``` I got:

    Automation Mode is disabled.
    This device DOES NOT REQUIRE user authentication to enable Automation Mode.

**Comment by erik-bershel** [comment]
@erikng new image on board. May I ask you to check if the issue still persist?

**Comment by idigra** [comment]
> @erikng new image on board. May I ask you to check if the issue still persist?

It's still failing for me - but it's weird: We have a pipeline with two parallel jobs (for debug and release), the debug job passed while the release job failed.

**Comment by erik-bershel** [comment]
Hey @idigra! 
Can you please check the Runner version? I suspect that the failed job was run with an old image (20230524.1), while the successful one was assigned to the new image (20230611.2).
For example:
 
<img width="316" alt="Screenshot 2023-06-15 at 23 00 49" src="https://github.com/actions/runner-images/assets/110455084/26b73793-40de-49e4-b9af-f0a7f92c6aee">

**Comment by idigra** [comment]
> Hey @idigra! Can you please check the Runner version? I suspect that the failed job was run with an old image (20230524.1), while the successful one was assigned to the new image (20230611.2). For example:
> 
> <img alt="Screenshot 2023-06-15 at 23 00 49" width="316" src="https://user-images.githubusercontent.com/110455084/246248628-26b73793-40de-49e4-b9af-f0a7f92c6aee.png">

Yes, that's right. Versions precisely matching the ones you mentioned.
Do we have any deadline that after it we're guaranteed that all available agents are updated?

**Comment by erik-bershel** [comment]
> > Hey @idigra! Can you please check the Runner version? I suspect that the failed job was run with an old image (20230524.1), while the successful one was assigned to the new image (20230611.2). For example:
> > <img alt="Screenshot 2023-06-15 at 23 00 49" width="316" src="https://user-images.githubusercontent.com/110455084/246248628-26b73793-40de-49e4-b9af-f0a7f92c6aee.png">
> 
> Yes, that's right. Versions precisely matching the ones you mentioned. Do we have any deadline that after it we're guaranteed that all available agents are updated?

Due to macOS 13 still being in beta, it's difficult for me to give an exact timeline. It shouldn't take more than a couple of working days, but I'll come back separately and let you know when everything is ready. I'm afraid I may have bothered you with checks too early this time.
cc @erikng @drewvolz

**Comment by idigra** [comment]
> > > Hey @idigra! Can you please check the Runner version? I suspect that the failed job was run with an old image (20230524.1), while the successful one was assigned to the new image (20230611.2). For example:
> > > <img alt="Screenshot 2023-06-15 at 23 00 49" width="316" src="https://user-images.githubusercontent.com/110455084/246248628-26b73793-40de-49e4-b9af-f0a7f92c6aee.png">
> > 
> > 
> > Yes, that's right. Versions precisely matching the ones you mentioned. Do we have any deadline that after it we're guaranteed that all available agents are updated?
> 
> Due to macOS 13 still being in beta, it's difficult for me to give an exact timeline. It shouldn't take more than a couple of working days, but I'll come back separately and let you know when everything is ready. I'm afraid I may have bothered you with checks too early this time. cc @erikng @drewvolz

Thanks! That's fine, for us it's not urgent. I can wait until we're sure that it's done. Also we're fine with small percentages of agents that are not upgraded, the only implication is that developers will be required to rerun which is a cost we can be tolerated for, as long as it's rare and is going to be solved.

**Comment by erikng** [comment]
Yes, I'm also waiting on the new image version as I have gone ahead and started doing development on Xcode 15 so the runner would fail the unit tests anyway now as some functionality is only in the new Swift 5.9 frameworks. It appears to only be 29% deployed out, but as soon as it's fully deployed, I can try it.

I will try it now and see if I get the luck of the draw with `Image Version: 20230611.2`

**Comment by erikng** [comment]
It's deployed to about 90% now so my luck of the draw was much better this morning. My unit tests are working now and I was able to cut a new pre-release of my application, including the use of Xcode 15.

Thanks!

**Comment by idigra** [comment]
Same here, tests are passing. Thanks!

**Comment by drewvolz** [comment]
Passing on my end. Thank you!

**Comment by erik-bershel** [comment]
@drewvolz @erikng @idigra all the agents are updated at the moment. Please feel free to open new issues in case of else concerns.

**Comment by sssuourabh** [comment]
@idigra i am still facing the issue.
<img width="1062" alt="Screenshot 2023-10-17 at 11 20 46 AM" src="https://github.com/actions/runner-images/assets/2918573/b189b200-06b1-484a-9577-68ac1ca45ff8">

**Comment by idigra** [comment]
> @idigra i am still facing the issue.

I guess you'd like to tag one of the issues owner rather than me, who only encountered this issue.
But as a preliminary check, I suggest to verify that you're using the same type of agent (MS hosted macOS-13), and to try the ```automationmodetool``` check as I mentioned [above](https://github.com/actions/runner-images/issues/7621#issuecomment-1586067223).

**Comment by sssuourabh** [comment]
@idigra where in the script i should add `automationmodetool` in pipeline?

**Comment by sssuourabh** [comment]
i added this  -   `automationmodetool enable-automationmode-without-authentication` but getting an error

**Comment by idigra** [comment]
> i added this - `automationmodetool enable-automationmode-without-authentication` but getting an error `Enter the password for user 'runner': Authentication failed, incorrect password or not an administrator. Error: Process completed with exit code 1.` @idigra

Sorry, too long ago, I don't remember the details.

**Comment by sssuourabh** [comment]
> @idigra i am still facing the issue. <img alt="Screenshot 2023-10-17 at 11 20 46 AM" width="1062" src="https://private-user-images.githubusercontent.com/2918573/275724649-b189b200-06b1-484a-9577-68ac1ca45ff8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NTQyMjYsIm5iZiI6MTcxMjU1MzkyNiwicGF0aCI6Ii8yOTE4NTczLzI3NTcyNDY0OS1iMTg5YjIwMC0wNmIxLTQ4NGEtOTU3Ny02OGFjMWNhNDVmZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDhUMDUyNTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjZhYzY0ZTk0YjMxZDI1MDEyMTQ3NGE2NTAyZDk5MzJmNTQzN2JlM2ZhNTgyNjk2ZmNiYWQ0ZjQzYTVhZDM2YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6CZmdVu0ms_07mqbAdqkwi1nN3fag-mDaKGPj68a1c0">

@erik-bershel

**Comment by erik-bershel** [comment]
Hey @sssuourabh!
What exactly you are doing or trying to do?

I checked automation-mode:
```yml

jobs:
  test:
    strategy:
      matrix:
        os: [ macos-12, macos-13, macos-14 ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Run command
      run: automationmodetool
    - name: Run command
      run: sudo /usr/sbin/DevToolsSecurity --enable
```
Got next (the same for all macOS images:
<img width="652" alt="Screenshot 2024-04-08 at 20 24 29" src="https://github.com/actions/runner-images/assets/110455084/2dcc1b47-151d-427b-817d-536415aea43f">

It seems fine. There is a possibility that you trying to use not authorised operation.

**Comment by erik-bershel** [comment]
Hey @sssuourabh!
This output is not related to the root issue. It looks more like project config issue than automation mode issue. "com.exampleidentifier.app" was not found. It's fair output for misconfigured run.

**Comment by sssuourabh** [comment]
@erik-bershel  Now when i solved that identifier problem then it says this problem.

<img width="1093" alt="Screenshot 2024-04-09 at 2 48 46 PM" src="https://github.com/actions/runner-images/assets/2918573/86ec3cbe-5b48-4229-b8a1-ed3a08afdb24">

**Comment by erik-bershel** [comment]
@sssuourabh please provide archive with logs and link to the failed run, no matter if private.

**Comment by sssuourabh** [comment]
I am attaching logs, please have a look. 
and thanks for such quick response from .

[logs_22566947746.zip](https://github.com/actions/runner-images/files/14916624/logs_22566947746.zip)

**Comment by erik-bershel** [comment]
Hey @sssuourabh!
Basing on the logs I may say next.
```t
2024-04-09T09:09:04.4786430Z 2024-04-09 09:09:02.669 xcodebuild[20053:114125]  iOSSimulator: 97C573C1-C829-42F5-8F4A-E13807B80A3B: Failed to launch app with identifier: com.doxel.app and options: {

```
This indicates that the application failed to run on the simulator with ID "com.doxel.app".

The reasons for this error may be different:

- Build problem: The application may not be built correctly or completely, resulting in a launch error.
- Simulator Problem: Sometimes the simulator may be not configured correctly.
- Test configuration problem: Your tests may be expecting a different configuration that doesn't match the actual application configuration.

To resolve this issue, you may need to follow these steps:

- Try running the app manually on the simulator from Xcode to make sure it launches correctly.
- Check your testing configuration in GitHub Actions to see if your application launch options need to be adjusted or a different configuration may need to be selected.
- Check that the simulator you are trying to run tests on is available and configured correctly.

**If you continue to experience problems after checking the above steps, you may need to analyse the simulator logs or build logs in more detail to identify the specific cause of the error.**

Separately, I would like to note that firstly I would try to run the same tests in the same way configured local environment. There is always a possibility that your test did not run simply because the base runner did not have enough resources. I can say right away that we have no influence on performance issues. Example of this kind: https://github.com/fastlane/fastlane/issues/21025#issuecomment-1435665269

Unfortunately, the problem is not in the automation itself - this is a simple problem to solve, but is located somewhere between the simulator and your application.

**Comment by sssuourabh** [comment]
hi @erik-bershel can you please check my logs my build is getting succeeded but TEST BUILD FAILED.

**Comment by erik-bershel** [comment]
Hey @sssuourabh! Please, update your message. There is no logs at all.

**Comment by sssuourabh** [comment]
<img width="812" alt="Screenshot 2024-05-18 at 10 24 22 A@erik-bershel rc="https://github.com/actions/runner-images/assets/2918573/d71be61f-7951-4708-84f2-403339b74aa0">
@erik-bershel
