### ISSUE TITLE
macOS 13 runner / Xcode 14.3.1 UI Testing - Timed out while enabling automation mode

### ISSUE THREAD

**Issue by zorgiepoo** [actions/runner-images#7778]
### Description

Similar to #7621 that @erik-bershel looked at, on my `macos-13` runner setting `DEVELOPER_DIR` to `/Applications/Xcode_14.3.1.app/Contents/Developer` I am getting a `Timed out while enabling automation mode` error:

```
	UI Tests-Runner (25570) encountered an error (The test runner failed to initialize for UI testing. If you believe this error represents a bug, please attach the result bundle at /Users/runner/work/Sparkle/Sparkle/build/Logs/Test/Test-UITests-2023.06.24_14-41-23-+0000.xcresult. (Underlying Error: Timed out while enabling automation mode.))
Test session results, code coverage, and logs:
```

This has happened twice so I don't think it's a coincidence. I have gotten `macos-13` to run successfully using Xcode 15 however (at least once).

More details on the runner:

```
Current runner version: '2.305.0'
Operating System
  macOS
  13.4
  22F66
Runner Image
  Image: macos-13
  Version: 20230524.1
  Included Software: https://github.com/actions/runner-images/blob/macos-13/20230524.1/images/macos/macos-13-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/macos-13%2F20230524.1
Runner Image Provisioner
  2.0.238.1
```

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/sparkle-project/Sparkle/actions/runs/5364813953/jobs/9733244971

### Is it regression?

Yes, doesn't occur using macos-12 and Xcode 14.2

### Expected behavior

UI tests should work with this combination (Xcode 14.3.1 and macOS 13)

### Actual behavior

UI tests don't start.

### Repro steps

Run macOS UI tests and have them fail

**Comment by mikhailkoliada** [comment]
it looks like you ran on image from may because some updates got stuck on our side, should be fixed now and all the images were updated to the version which has the ui call fix enabled.

**Comment by sssuourabh** [comment]
@mikhailkoliada how you solved this issue i am still facing this issue.
