### ISSUE TITLE
Unit Test are failing randomly on Xcode 15

### ISSUE THREAD

**Issue by sushimatou** [actions/runner-images#8472]
### Description

When using new Xcode 15 in Unit Test job in GitHub Action pull request workflow, some test are randomly failing (it seems to be asynchronous tests most of the time, but not always). 

Command ran is `sudo xcode-select -s /Applications/Xcode_15.0.app`

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

Version: 20231002.1

### Is it regression?

Version: 20231002.1

### Expected behavior

Tests should work as when we runned them with Xcode 14. (`sudo xcode-select -s /Applications/Xcode_14.3.app`)

### Actual behavior

Tests are randomly failing.

### Repro steps

In the workflow: 
`sudo xcode-select -s /Applications/Xcode_14.3.app`
[...]
`set -o pipefail && xcodebuild -workspace Project.xcworkspace -scheme Project -derivedDataPath DerivedData -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=16.4,name=iPhone 14' -enableCodeCoverage YES -IDEBuildingContinueBuildingAfterErrors=YES CI='github' test | bundle exec xcpretty -s`

**Comment by Alexey-Ayupov** [comment]
Hello, @sushimatou. We will take a look.

**Comment by Alexey-Ayupov** [comment]
This issue looks similar to this one https://github.com/actions/runner-images/issues/7971, we are working on that.

**Comment by honkmaster** [comment]
Xcode 15.0.1 RC is released.

https://developer.apple.com/documentation/xcode-release-notes/xcode-15_0_1-release-notes

"Fixed: Executing Unit/UI tests from Xcode on the iOS Simulator takes an extended time to launch on first run of the suite. (115187363) (110330776) (FB12237092)"

Let's hope the release comes sooner than later and will be deployed here fast.

**Comment by gabe4coding** [comment]
With Xcode 15.0.1 the issue is still present, and the run of the tests is extremely slow

**Comment by mihael-weareyou** [comment]
> With Xcode 15.0.1 the issue is still present, and the run of the tests is extremely slow

Second that. Xcode 15.0.1 on the pipeline and the unit tests are hanging for more than 30 minutes which causes the pipeline to fail.

**Comment by chriswooden** [comment]
We've gone from average 6-13 min build times on 14.3.1, to 35 mins to 2 hours since 15.0.1 (still the odd timeout)... guess we're waiting on 15.1 then 😞
