### ISSUE TITLE
Ubuntu 20.04 build fails on kotlin hash validation

### ISSUE THREAD

**Issue by nlighten** [actions/runner-images#8707]
### Description

For the latest release we get the following error during build:

```
==> azure-arm: Provisioning with shell script: /home/runner/work/virtual-environments/images/linux/scripts/installers/kotlin.sh
    azure-arm: Downloading 'https://github.com/JetBrains/kotlin/releases/download/v1.9.20/kotlin-compiler-1.9.20.zip' to '/tmp/kotlin-compiler.zip'...
    azure-arm: Download completed
==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
...........
```

There is no specific error but running `kotlin.sh` locally with `-x` gives the following hint:

```
++ matching_line='- [KT-32275](https://youtrack.jetbrains.com/issue/KT-32275) Embedding kotlin-compiler-embeddable into a Java EE App leads to CDI related deployment error
' kotlin-compiler-1.9.20.zip | 15a8a2825b74ccf6c44e04e97672db802d2df75ce2fbb63ef0539bf3ae5006f0 |
+++ echo '- [KT-32275](https://youtrack.jetbrains.com/issue/KT-32275) Embedding kotlin-compiler-embeddable into a Java EE App leads to CDI related deployment error
' kotlin-compiler-1.9.20.zip | 15a8a2825b74ccf6c44e04e97672db802d2df75ce2fbb63ef0539bf3ae5006f0 |
+++ wc -l
++ [[ 2 -gt 1 ]]
++ echo 'Multiple lines found included the file kotlin-compiler. Please specify a more specific file name.'
++ exit 1
+ kotlin_hash='Multiple lines found included the file kotlin-compiler. Please specify a more specific file name.'
+ use_checksum_comparison /tmp/kotlin-compiler.zip 'Multiple lines found included the file kotlin-compiler. Please specify a more specific file name.'
+ local file_path=/tmp/kotlin-compiler.zip
+ local 'checksum=Multiple lines found included the file kotlin-compiler. Please specify a more specific file name.'
+ local sha_type=256
+ echo 'Performing checksum verification'
Performing checksum verification
+ [[ ! -f /tmp/kotlin-compiler.zip ]]
++ shasum --algorithm 256 /tmp/kotlin-compiler.zip
++ awk '{print $1}'
+ local_file_hash=15a8a2825b74ccf6c44e04e97672db802d2df75ce2fbb63ef0539bf3ae5006f0
+ [[ 15a8a2825b74ccf6c44e04e97672db802d2df75ce2fbb63ef0539bf3ae5006f0 != \M\u\l\t\i\p\l\e\ \l\i\n\e\s\ \f\o\u\n\d\ \i\n\c\l\u\d\e\d\ \t\h\e\ \f\i\l\e\ \k\o\t\l\i\n\-\c\o\m\p\i\l\e\r\.\ \P\l\e\a\s\e\ \s\p\e\c\i\f\y\ \a\ \m\o\r\e\ \s\p\e\c\i\f\i\c\ \f\i\l\e\ \n\a\m\e\. ]]
+ echo 'Checksum verification failed. Expected hash: Multiple lines found included the file kotlin-compiler. Please specify a more specific file name.; Actual hash: 15a8a2825b74ccf6c44e04e97672db802d2df75ce2fbb63ef0539bf3ae5006f0.'
Checksum verification failed. Expected hash: Multiple lines found included the file kotlin-compiler. Please specify a more specific file name.; Actual hash: 15a8a2825b74ccf6c44e04e97672db802d2df75ce2fbb63ef0539bf3ae5006f0.
+ exit 1
```

So it seems that `get_github_package_hash` cannot determine the correct hash due to multiple lines matching `kotlin-compiler`.

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

ubuntu20/20231030.2

### Is it regression?

Any version not containing https://github.com/actions/runner-images/pull/8596

### Expected behavior

Build succeeds

### Actual behavior

build fails. See description above.

### Repro steps

Build latest ubuntu 20.04 image

**Comment by erik-bershel** [comment]
Hey @nlighten!

In progress here https://github.com/actions/runner-images/pull/8704.

**Comment by nlighten** [comment]
Hi @erik-bershel ,

That was a super quick response. I searched the issues but missed this PR. Sorry for that.

I'll wait for the fix then.

**Comment by mikhailkoliada** [comment]
should be fixed in main, do not forget to sync :)

**Comment by drazkiewicz** [comment]
I did run both Windows and Linux pipelines on Saturday - the error is still there.
