### ISSUE TITLE
Template file names do not match the code in GenerateResourcesAndImages

### ISSUE THREAD

**Issue by Noel-Jones** [actions/runner-images#8813]
### Description

Files are named ubuntu-20.04.json and ubuntu-22.04.pkr.hcl

Code looks for files without the period. Other appear to be correct.

Builds fail.

````
        ([ImageType]::Windows2019) {
            $relativeTemplatePath = Join-Path "windows" "templates" "windows-2019.json"
        }
        ([ImageType]::Windows2022) {
            $relativeTemplatePath = Join-Path "windows" "templates" "windows-2022.json"
        }
        ([ImageType]::Ubuntu2004) {
            $relativeTemplatePath = Join-Path "ubuntu" "templates" "ubuntu-2004.json"
        }
        ([ImageType]::Ubuntu2204) {
            $relativeTemplatePath = Join-Path "ubuntu" "templates" "ubuntu-2204.pkr.hcl"
        }
        ([ImageType]::UbuntuMinimal) {
            $relativeTemplatePath = Join-Path "ubuntu" "templates" "ubuntu-minimal.pkr.hcl"
````

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [X] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

master

### Is it regression?

It worked a week or so ago

### Expected behavior

Should be able to find the template files.

### Actual behavior

Build fails as it cannot find the template file.

### Repro steps

Do a build using GenerateResourcesAndImage

**Comment by Noel-Jones** [comment]
I'd be grateful if anyone could explain why builds are only supported from master (as I keep reading elsewhere) when master is, particularly at this time of refactoring, subject to such frequent change. Am I correct in my understanding of this or should I be building from a release tag? I can kinda understand that the build is dependent upon upstream repositories that cannot be guaranteed to be the same even when building from a release tag but it seems like being caught between a rock and a hardplace if I want to automate a weekly or monthly build.

**Comment by mjlally07** [comment]
For Windows2022 image selection, Join-path seems to have problem with not accepting "windows-2022.json" path value.

**Comment by Alexey-Ayupov** [comment]
Hello @Noel-Jones. Could you please update your fork? It looks like you have an outdated version of this file.

**Comment by Noel-Jones** [comment]
Hi, this appears to have been resolved in PR #8815. Thanks.

**Comment by tumm0283** [comment]
Hi, Are the changes committed to main? i still see the ubuntu-22.04 version file

**Comment by tumm0283** [comment]
> > Hi, Are the changes committed to main? i still see the ubuntu-22.04 version file
> 
> yes, but GenerateResourcesAndImages was change to match the template file names.

Hi Noel, i still don't see the changes on GenerateResourcesAndImages it still has the files with periods under main ..and our builds are still failing on this error 
![linperiod](https://github.com/actions/runner-images/assets/29237351/6795ea6d-771b-4a81-81e7-8028d10aab82)
sorry if i am looking in wrong spot ..can you please advise. Thank you

**Comment by Noel-Jones** [comment]
tumm0283 - If you are calling GenerateResourcesAndImages directly then I think you are hitting the same problem that I lost an afternoon over. Three of the arguments have changed from Boolean to Switch which leads to apparently random issues with positional parameters.

- RestrictToAgentIpAddress
- Force
- ReuseResourceGroup

If you were setting any to true then you need to remove the true. If you were setting any to false then you need to remove the switch. 

There have been so many changes recently like this one that I have spent this morning changing my pipeline to call the packer template directly.

**Comment by tumm0283** [comment]
> tumm0283 - If you are calling GenerateResourcesAndImages directly then I think you are hitting the same problem that I lost an afternoon over. Three of the arguments have changed from Boolean to Switch which leads to apparently random issues with positional parameters.
> 
> * RestrictToAgentIpAddress
> * Force
> * ReuseResourceGroup
> 
> If you were setting any to true then you need to remove the true. If you were setting any to false then you need to remove the switch.
> 
> There have been so many changes recently like this one that I have spent this morning changing my pipeline to call the packer template directly.

Hi Noel, Thanks again! We are calling the GenerateResourcesAndImage psi directly, i don't have any settings or arguments passing in our pipeline.
this is how we have been calling the task.
![lingenerate](https://github.com/actions/runner-images/assets/29237351/6290723c-df16-4d01-90f7-2c158af759f7)

any help appreciated.

**Comment by Noel-Jones** [comment]
tun0283 - It's almost impossible to debug, based on the info given. I am not part of the team developing runnier-images, just a user like yourself. I can only re-iterate that there have been breaking changes to the standalone use of GenerateResourcesAndImage. It has code to support different powershell versions so this could be a factor, and the parameter passing has changed. There are no positional parameters so the error you are getting implies that it thinks there is. The fact that it reports the packer template file as the issue implies the problem is inside of the function so I'd suggest raising it as a new issue with as much supporting info as you can. I'd guess maybe the template path has a space in it so I'd look at the value of ImageGenerationRepositoryRoot. It is also interesting that the function is not used anywhere else in the repository which suggests to me that it not on a strategic road map. Either way, I stopped using it and the code I now run is actually very similar to what is in build-image.ps1 Hope some of this helps and good luck!
