### ISSUE TITLE
[ WIN22] Microsoft Edge WebDriver Signature thumbprint do not match expected

### ISSUE THREAD

**Issue by saoullabit** [actions/runner-images#8884]
### Description

Hi,
using the last realse to build the agents, the build fails at the step:  ==> `image: Provisioning with powershell script: C:\virtual-environments\images\windows\templates/../scripts/build/Install-EdgeDriver.ps1`
The error is: 
```
==> image: Signature thumbprint do not match expected.
==> image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:734 char:9
==> image: +         throw "Signature thumbprint do not match expected."
==> image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
```
We have tried 3 times to build the image and we still face an issue at this step.

Is there is way to fix it ?

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

https://github.com/actions/runner-images/releases/tag/win22%2F20231115.2

### Is it regression?

Yes, win22/20230109.1 (https://github.com/actions/runner-images/releases/tag/win22%2F20230109.1)

### Expected behavior

no issue :) 

### Actual behavior

build fails

### Repro steps

build an image and wait till the error appears.

**Comment by mikhailkoliada** [comment]
Hello! Please build your image from the main brand as we do not guarantee that the tags are functional, the issue has been addressed in main few days ago.

**Comment by saoullabit** [comment]
Sorry ?
You "do not guarantee that the tags are functional" ?
I've downloaded yesterday the runner and it is supposed to bring the fix within ... Anyway I'll try main.
Maybe I'll be back

**Comment by ihari277** [comment]
I am trying it from the main branch, but I am still having the issue.

    azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:734 char:9
==> azure-arm.image: +         throw **"Signature thumbprint do not match expected."**

**Comment by algazod** [comment]
Still having the issue on the main branch.

`azure-arm.image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory`

==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:734 char:9
==> azure-arm.image: + throw "Signature thumbprint do not match expected."

**Comment by ihari277** [comment]
it is fixed now

**Comment by mnieto** [comment]
I continue getting the error from the main branch

```
==> image: Provisioning with powershell script: C:\agent\_work\3\s\images\windows\templates/../scripts/build/Install-EdgeDriver.ps1
    image: Get the Microsoft Edge WebDriver version...
    image:
    image:
==> image: Signature thumbprint do not match expected.
    image:     Directory: C:\SeleniumWebDrivers
    image:
    image:
    image: Mode                 LastWriteTime         Length Name
    image: ----                 -------------         ------ ----
    image: d-----        12/19/2023  11:44 PM                EdgeDriver
    image: Downloading package from https://msedgedriver.azureedge.net/LATEST_RELEASE_120_WINDOWS to C:\SeleniumWebDrivers\EdgeDriver\versioninfo.txt...
    image: Package downloaded in 0.05 seconds
    image: Download Microsoft Edge WebDriver...
    image: Downloading package from https://msedgedriver.azureedge.net/120.0.2210.77/edgedriver_win64.zip to C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip...
    image: Package downloaded in 0.06 seconds
    image: Expand Microsoft Edge WebDriver archive...
    image: Expand archive 'C:\Users\packer\AppData\Local\Temp\edgedriver_win64.zip' to 'C:\SeleniumWebDrivers\EdgeDriver' directory
==> image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> image: +         throw "Signature thumbprint do not match expected."
==> image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.

```

**Comment by michaelmowry** [comment]
I have synced the latest main branch and this error is still occurring on the win22 image build

**Comment by ihari277** [comment]
I tied in win 22 still Facing the same issue

+ CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
+ FullyQualifiedErrorId : Signature thumbprint do not match expected.
