### ISSUE TITLE
Windows agent image failed

### ISSUE THREAD

**Issue by jaswant-dnv** [actions/runner-images#9118]
### Description

   Windows agent image failed
   
   azure-arm.image: Error - hashes do not match. Actual value was 'F188236C4BCC8421169917A1141A4913430A4149B1CF01CBB65FB33805437070'.
    azure-arm.image: ERROR: Checksum for 'C:\Users\packer\AppData\Local\Temp\chocolatey\swig\4.1.1\download' did not meet '2ec3107e24606db535d77ef3dbf246dc6eccbf1d5c868dce365d7f7fb19a1a51' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
    azure-arm.image: The install of swig was NOT successful.
    azure-arm.image: Error while running 'C:\ProgramData\chocolatey\lib\swig\tools\chocolateyinstall.ps1'.
    azure-arm.image:  See log for details

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image 20231217.2.0

### Is it regression?

NA

### Expected behavior

Build image for agents

### Actual behavior

azure-arm.image: Error - hashes do not match. Actual value was 'F188236C4BCC8421169917A1141A4913430A4149B1CF01CBB65FB33805437070'.
    azure-arm.image: ERROR: Checksum for 'C:\Users\packer\AppData\Local\Temp\chocolatey\swig\4.1.1\download' did not meet '2ec3107e24606db535d77ef3dbf246dc6eccbf1d5c868dce365d7f7fb19a1a51' for checksum type 'sha256'. Consider passing the actual checksums through with --checksum --checksum64 once you validate the checksums are appropriate. A less secure option is to pass --ignore-checksums if necessary.
    azure-arm.image: The install of swig was NOT successful.
    azure-arm.image: Error while running 'C:\ProgramData\chocolatey\lib\swig\tools\chocolateyinstall.ps1'.
    azure-arm.image:  See log for details

### Repro steps

rerun piepeline

**Comment by Alexey-Ayupov** [comment]
Hello @jaswant-dnv, we do not observe such issue on our nightly builds. Could you please provide more information, such as where you perform your build. Also please check that you have the updated version of your fork.

**Comment by jaswant-dnv** [comment]
We perform this using ADO pipeline with ubuntu agents.
Yes updated repo was forked every time we run this weekly job.

We did performed rerun

##[debug]Agent running environment resource - Disk: available:26322.00MB out of 85160.00MB, Memory: used 96MB out of 15981MB, CPU: usage 0.33
    azure-arm.image: Package downloaded in 9.06 seconds
==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
==> azure-arm.image: Provisioning step had errors: Running the cleanup provisioner, if present...
==> azure-arm.image:

**Comment by mikhailkoliada** [comment]
should be fixed, sync your main.

**Comment by jaswant-dnv** [comment]
Not fixed yet.

==> azure-arm.image: Signature thumbprint do not match expected.
==> azure-arm.image: At C:\Program Files\WindowsPowerShell\Modules\ImageHelpers\InstallHelpers.ps1:972 char:9
==> azure-arm.image: +         throw "Signature thumbprint do not match expected."
==> azure-arm.image: +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
==> azure-arm.image:     + CategoryInfo          : OperationStopped: (Signature thumb...match expected.:String) [], RuntimeException
==> azure-arm.image:     + FullyQualifiedErrorId : Signature thumbprint do not match expected.
==> azure-arm.image:
